### ISSUE TITLE
Tooltip background is applied to EOL when default face is remapped

### ISSUE THREAD

**Issue by hlissner** [company-mode/company-mode#1019]
https://github.com/company-mode/company-mode/commit/e1d58370cf1f6b42b929376eab2193bfc0914381 (the fix for #996) introduced [an issue](https://github.com/hlissner/emacs-solaire-mode/issues/37) that is present when the `default` face is remapped using the `face-remap` library:

![image](https://user-images.githubusercontent.com/510883/95162253-382c6880-0773-11eb-89f7-19f021349472.png)

The overlay's background is fontified to EOL.

This can be fixed by either:

1. Removing the hard-coded `:background`:

   ```diff
        (let* ((nl-face (list
                         :extend t
   -                     :inverse-video nil
   -                     :background (face-attribute 'default :background)))
   +                     :inverse-video nil)
               (str (apply #'concat
                           (when nl " \n")
                           (cl-mapcan
   ```

2. Or looking up `default`'s remap:

   ```diff
        (let* ((nl-face (list
                         :extend t
                         :inverse-video nil
   -                     :background (face-attribute 'default :background)
   +                     :background
   +                     (face-attribute
   +                      (if-let (remap (cadr (assq 'default face-remapping-alist)))
   +                          (if (keywordp (car-safe remap))
   +                              (plist-get remap :background)
   +                            remap)
   +                        'default)
   +                      :background
   +                      nil t)))
               (str (apply #'concat
                           (when nl " \n")
                           (cl-mapcan
   ```

Would you be open to a PR for one of these solutions? (I'll factor out the `if-let` for backwards compatibility if I do)

----

Just realized this is the same issue as https://github.com/company-mode/company-mode/issues/1013.

**Comment by dgutov** [comment]
Hi!

Thanks for the clear scenario. So that's what that other report was about.

e1d5837 was not a fix for #996, but rather a preparation for an alternative solution. Which may still be reverted, if that solution never materializes in the end. But I'm keeping it for now. Let's talk how to improve it.

> Removing the hard-coded :background:

That would break the fix for the problem described in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=42552#23 (there is a link just 4 lines below that code).

> Or looking up default's remap:

Sure, sounds reasonable. Preferably this would also be accompanied by extracting the code to a "private" utility function.

I'd be happy to see a PR, but you haven't signed the FSF CA papers, right? If so, the total size of the change shouldn't exceed 15 lines.

**Comment by hlissner** [comment]
> I'd be happy to see a PR, but you haven't signed the FSF CA papers, right? If so, the total size of the change shouldn't exceed 15 lines.

Sure thing. I'll have a PR up shortly.

No I have not signed the papers, but 15 lines should be more than enough to work with. Does that line count include comments?

**Comment by dgutov** [comment]
> Does that line count include comments?

Yes.

But some lines could be discounted as "mechanical" changes, so it's not an exact number.

BTW, it you fancy to get started on that assignment anyway (after resolving this issue), I'd be happy to send you the instructions.
