### ISSUE TITLE
company-files: why are trailing slashes for directories not inserted?

### ISSUE THREAD

**Issue by cwfoo** [company-mode/company-mode#1042]
Why are trailing slashes for directories not inserted even though they are shown in the completion list?

Suppose the completion candidates are `/home/user1/` and `/home/user2/`. If I press <kbd>Enter</kbd> to insert `/home/user1/`, only `/home/user1` will actually be inserted. Note the missing slash. This is unexpected behaviour because what is actually inserted is different from what is shown in the list of completion candidates.

It appears that this unexpected behaviour was originally implemented by #465 (@vspinu). The relevant lines in company-mode 0.9.13 are:

https://github.com/company-mode/company-mode/blob/656ad10670512e135a0a5881f127bb7a789ef8ca/company-files.el#L130-L132

What is the reason for this behaviour? How do I retain the trailing slash when I complete a directory path?

**Comment by dgutov** [comment]
One reason to do this is that you can type `/` again to automatically continue completion (and insert of of the members of that directory instead). Whereas for most purposes (scripts, programs, etc) you don't really need that trailing slash, so it's not a hindrance.

Check out the discussion here: https://github.com/company-mode/company-mode/pull/465#discussion-diff-51400242

Another reasons is that we've been doing that for a long time...

**Comment by cwfoo** [comment]
@dgutov What is the proper way to disable this behaviour?

I am currently using something like this:

```
(eval-after-load "company"
  (advice-add 'company-files--post-completion
                      :around
                      (lambda (orig-fun &rest args) nil)))
```

**Comment by dgutov** [comment]
@cwfoo You can use `#'ignore` instead of the anonymous lambda.

I can add a user option for this, but I'd like to see at least a second user making the same request.

**Comment by cwfoo** [comment]
I think I now understand the reason behind the existing implementation. The trailing slash is omitted so that the user can trigger autosuggestion for subdirectories by typing the trailing slash. This takes some time to get used to. Closing this issue.

**Comment by bard** [comment]
@cwfoo @dgutov thanks for providing the workaround.

> I can add a user option for this, but I'd like to see at least a second user making the same request.

I'll be the second user making that request. I'll try to give an objective argument — apologies in advance for exploding a microinteractions into a macro exposition.

The current behiavor creates 1) a special case 2) inside a frequent interaction which often has 3) a tight feedback loop.

The general case is that what is displayed as completion, is kept as completion. The only other exception I can think of is, when writing TypeScript with LSP, an optional property gets completed as "prop?", only for the question mark to disappear when you continue writing. (I write TypeScript for a living and that still throws me off.)

Special cases add a mental step, where you can no longer rely on just the signal (the displayed completion), but have to take the context into account (what is the nature of the thing I'm completing). When a special case happens in frequent interactions  (completing a path in a shell buffer) several times (a /path/can/have/many/components), the problem is compounded.

One can get used to it, in principle, but I'd argue that requesting extra work of users should always come with offering an upside, which in this case I don't see.

So, please consider adding the option. I'd even dare suggest to test and see if people used to the old behavior can immediately pick up the new one (I think that's a fair chance), which would be an argument for changing the default, but we don't really have an easy way to do A/B in Emacsland and I understand if you don't want to go there.

**Comment by cwfoo** [comment]
@bard I have written a replacement for company-files: https://github.com/cwfoo/company-dirfiles. You may find it more comfortable to use. I based its behavior on Vim's built-in filename completion (which does not have surprising behavior).

Would you like me to reopen this issue?

**Comment by bard** [comment]
Thanks for the follow-up @cwfoo! I just tried company-dirfiles. I'll stick with company-files+workaround since it matches what you get in bash (`/ho<TAB>` prints `/home/`), plus makes the common case (>1 path parts) faster, e.g. for `/home/bard/projects/foo`:

- `/ho<TAB>ba<TAB>pro<TAB>fo` (company-files with workaround)
- `/ho<TAB>/ba<TAB>/pro<TAB>fo` (company-dirfiles, or company-files without workaround)

As for reopening, it's up to how you feel about the issue; I think there's a chance to make a small but frequent interaction faster for many (company-mode being the de-facto completion framework for Emacs), but I've already applied the workaround so it doesn't make a practical difference for me.

**Comment by dgutov** [comment]
@cwfoo Looking at your backend, it seems to pretty much do the same thing regarding the disputed behavior: "Directories in the suggestions list do not have trailing slashes". The difference is only in how it is displayed.

Other differences:

> Adds company-mode annotations to distinguish between files and directories

If you enable icons in the latest version of `company-mode`, they also serve as type annotations, but more compact ones. I think that is better than the more verbose `[file]` and `[dir]`.

> Shows suggestions for one directory level only. Does not show suggestions from subdirectories.

Is the delay really long sometimes? I've never noticed that. Perhaps I'm spoiled with SSDs lately.

I don't mind changing this part of the behavior, or making it configurable. @bard, what do you think about this one, BTW?

**Comment by dgutov** [comment]
@bard I've pushed a new option, `company-files-chop-trailing-slash`.

Regarding this, though:

> One can get used to it, in principle, but I'd argue that requesting extra work of users should always come with offering an upside, which in this case I don't see.

The upside is that you can quickly make the popup show up again by typing `/`. Your example of `/ho<TAB>/ba<TAB>/pro<TAB>fo` requires the user to know the file names in advance, which is not always possible.

**Comment by bard** [comment]
> @bard I've pushed a new option, `company-files-chop-trailing-slash`.

:100: !

> > Shows suggestions for one directory level only. Does not show suggestions from subdirectories.
> 
> Is the delay really long sometimes? I've never noticed that. Perhaps I'm spoiled with SSDs lately.
> 
> I don't mind changing this part of the behavior, or making it configurable. @bard, what do you think about this one, BTW?

About showing suggestions from subdirectories? It isn't slow for me either, and while I'm also on an SSD machine, it's very much a low-end one.

> The upside is that you can quickly make the popup show up again by typing /. Your example of /ho<TAB>/ba<TAB>/pro<TAB>fo requires the user to know the file names in advance, which is not always possible.

Hmm, because of the above (showing subdirectories) the completions would be visible already, no? When I type `/ho`, the popup displays `/home` and `/home/bard`.

**Comment by dgutov** [comment]
> About showing suggestions from subdirectories? It isn't slow for me either, and while I'm also on an SSD machine, it's very much a low-end one.

There might be other benefits to the change: like the more streamlined flow if one uses RET to select completions.

If you manage to continue typing while only sometimes hitting TAB, the current behavior indeed works faster. RET can be attractive, though, when the directory you want is at the first position but there are several similarly named ones to TAB doesn't help you much. And we also have the `company-tng` workflow where TAB does something completely different, always breaking out of completion.

So I'm not sure which approach is the best here. It's a compromise either way.

> Hmm, because of the above (showing subdirectories) the completions would be visible already, no? When I type /ho, the popup displays /home and /home/bard.

This is about a workflow using RET again.

While the popup does show subdirectories as well, it's limited by 10 lines or so, and you can always have more directories, and the one you wanted might be near the end of the list (concealed). Then, if you pressed RET, you kind of have had to remember the names in the list in advance (before the popup closed); whereas auto-completion's goal is generally to try to relieve the user from that obligation.

**Comment by cwfoo** [comment]
> > Shows suggestions for one directory level only. Does not show suggestions from subdirectories.
>
> Is the delay really long sometimes? I've never noticed that. Perhaps I'm spoiled with SSDs lately.

I experience one or two noticeable delays during most sessions.  I would say that the delay is typically 300-500 ms, but sometimes longer (but rarely). I am not sure about the fundamental cause of the delay. This might be difficult to reproduce.

**Comment by dgutov** [comment]
> I use Emacs inside a VM on a HDD computer. This might explain the slowness.

That might do it. *shrug* I was also thinking that maybe you have some live Tramp connections (which would be a bug -- a slowdown from that -- but I would not be too surprised).
