### ISSUE TITLE
Input lag when using some backends

### ISSUE THREAD

**Issue by otavioschwanck** [company-mode/company-mode#1056]
Hi,

I'm a ruby deveoper and i'm using Emacs for +/- 2 years.

Some issue that i face on emacs that dont see in another editor (i was a vim user), is the input lag when some backends are running.

For now, i'm using only `company-dabbrev-code` with `company-robe` binded to a keybinding to use when i really need.

A few months ago i tried company-tabnine and really liked, but faced laggy when typing too.  I type and the letter take +/- 300 milliseconds to show on editor, and few like i'm using Eclipse IDE on 2000s.

I tested same plugins on vim with CoC, (tabnine, LSP for ruby) and had 0 lag.

I'm currently using doom emacs, here is my config:  https://github.com/otavioschwanck/doom_emacs_dotfiles/blob/master/company.el

Seems like company is using the same "process" of the typing and is getting over it.

Isn't possible to run company on a different process or something like that ?

Thanks for your time!

**Comment by dgutov** [comment]
Hi!

Which exact backends? What version of Emacs are you using?

> Seems like company is using the same "process" of the typing and is getting over it.

Elisp interpreter is single-threaded (and I think Vimscript is too?), but we can interact with external processes asynchronously. Any pre/postprocessing of interactions with said processes has to happen in the same thread, though. So at least with some LSP servers the speed of parsing JSON has been a significant bottleneck. Not since Emacs 27, though, or so I heard.

**Comment by otavioschwanck** [comment]
I'm using emacs 28 (with GCCemacs), The exact backends is company-robe (from robe) and company-tabnine.  They dont use LSP.

**Comment by dgutov** [comment]
> I'm using emacs 28 (with GCCemacs)

That's good. Should eliminate the biggest issues related to JSON parsing.

> The exact backends is company-robe (from robe) and company-tabnine.

And that's surprising, given how https://github.com/dgutov/robe/issues/127 went.

But here's how you can check where the responsibility lies: does using `company-dabbrev-code` exhibit the same problem? If not, it's most likely due to processing in each individual backend. The only way to deal with that would be to report the problem to each project, and probably do some benchmarking/investigations yourself.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html should help with the latter.

Looking at https://github.com/TommyX12/company-tabnine/issues/39, you have reported it previously, and for some reason or other, it went nowhere. I can't help with Tabnine. I could help with Robe if it does exhibit the same issue, assuming you stay around for the troubleshooting, if needed.

**Comment by otavioschwanck** [comment]
> But here's how you can check where the responsibility lies: does using company-dabbrev-code exhibit the same problem? 
No, with  `company-dabbrev-code` it works flawless.

> could help with Robe if it does exhibit the same issue, assuming you stay around for the troubleshooting, if needed.

I did some tests with robe, and if i don't use :separate, and use like '(company-robe company-dabbrev-code), works very well.  I just need to realize how to remove the duplicates now :(.  Closing the issue!

**Comment by dgutov** [comment]
Do you see the need for `company-dabbrev-code` in that combination often?

Robe tries to cover the common cases by including local and instance variables in its completions, for example.

**Comment by dgutov** [comment]
Is there some performance problem that `:separate` causes?
