### ISSUE TITLE
how should backends attach metadata to empty prefix strings?

### ISSUE THREAD

**Issue by dwang20151005** [company-mode/company-mode#1057]
Lots of context in case I'm asking the wrong question:

I'm building a company backend for the key words of a domain-specific language. Imagine a SQL backend where you could type `SELECT * O<Tab>` and it would suggest `ON`, `ORDER BY`, `OFFSET`, but not `ONLY`, because it understands that `ONLY` must be in a `FROM` expression.

I think the way to fit this into the company-mode API is by returning a prefix string containing the current token (here, `O`), plus some kind of metadata containing the incomplete AST up to that token.

I found a [tutorial](http://sixty-north.com/blog/a-more-full-featured-company-mode-backend.html) that suggests using text properties to annotate candidates with extra metadata. Text properties don't work as well for prefixes because prefixes are often the empty string, and it looks like `(text-properties-at 0 s)` returns `nil` when `s` is `""`.

(Actually, I made text properties work by representing the empty string as a string containing `U+200B ZERO-WIDTH SPACE`. It looks right and has characters on which I can hang text properties. But I assume that is not the right way to go.)

So, what is the right way to attach metadata to a prefix string?

**Comment by dgutov** [comment]
Yeah, it doesn't work for the prefix string exactly because it could be empty.

You can simply define a global private buffer-local variable. It will contain whatever metadata you wanted to associate with the latest prefix returned by your backend. Since only one value of prefix is at play at a given time, this should work fine. Add `no-cache` to your backend, though.

Alternatively, you can try using the `completion-at-point-functions` API and keep the association with metadata using a lexical scope, the list value returned by the completion function contains "completion table" which can be a closure accessing the metadata in the containing scope.

Someday we'll add some sort of "session" object. Not today, though.

**Comment by dwang20151005** [comment]
I defined a global private variable and it works, thanks!
