### ISSUE TITLE
"Matching input is required" on open-paren if no-cache and some candidates start with open-paren

### ISSUE THREAD

**Issue by dwang20151005** [company-mode/company-mode#1058]
Hi, me again. I am building a company backend for completion of an S-expression based domain-specific language. I would like to offer people a mixture of candidates that begin with an open-paren and candidates that do not. Also, I need to use `no-cache`, because of #1057.

I thought I could just return all my candidates, and let the user type to narrow the candidates, but company-mode seems to drop the candidates that start with open-paren.

Reproduction:

1. Run `emacs -q -L $COMPANY_MODE -l $REPRO_SCRIPT` where `COMPANY_MODE` is a copy of company mode and `REPRO_SCRIPT` is as follows:

      ```elisp
      (require 'company)
      (require 'cl-lib)

      (defun my-candidate-p (prefix) `(lambda (candidate) (string-prefix-p ,prefix candidate)))

      (defun my-candidates () '("foo" "(foo" "(fobar"))

      (defun my-backend (operation &optional arg &rest rest)
        (interactive (list 'interactive))
        (cl-case operation
          (interactive (company-begin-backend 'my-backend))
          (prefix (buffer-substring (line-beginning-position) (point)))
          (candidates (cl-remove-if-not (my-candidate-p arg) (my-candidates)))
          (no-cache t)
          ))

      (company-mode)
      (setf company-frontends '(company-pseudo-tooltip-frontend))
      (setf company-backends '(my-backend))
      (define-key global-map (kbd "TAB") 'my-backend)
      ```

2. In the `*scratch*` buffer, type `TAB`. As expected, see the tooltip with `foo`, `(foo`, and `(fobar`.

3. Type `(`.  Expect to see the tooltip narrow itself to only `(foo` and `(fobar`.  Instead, get the error "Matching input is required."

Here's my `company-diag` output:

```
Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-09-21 on igm-qws-u12673b
Company 0.9.13

company-backends: (my-backend)

Used backend: my-backend
Major mode: emacs-lisp-mode
Prefix: ""
Completions:
  "foo"
```

If my backend returns only `'("(foo" "(fobar")`, then I can type the `(` and subsequent letters to narrow the candidates.

If my backend responds `nil` to `no-cache`, then again I can type the `(` to narrow the candidates.

Can you reproduce?  What is the right way to do this?

**Comment by dgutov** [comment]
The rule is that the value of `prefix` should be consistent with what strings you return in `candidates`.

So, for instance, if company inserts a part of a string returned in `candidates` (usually following the complete-common logic path), the `prefix` action, when called on new location, should return the old prefix with the new part appended. If the backend returns a different (probably much shorter) prefix, company considers this to be a failed completion.

That said, the example you're giving above satisfies that rule, and seems to be caused by a certain bug in company, you could say. Namely: it destructively modifies the value that `candidates` returns, in `company--preprocess-candidates` during sorting.

You can work around that by either using

```el
(defun my-candidates () (list "foo" "(foo" "(fobar"))
```

as the definition, or by also responding with non-nil to `sorted`.

I've avoided fixing this as this behavior has a certain advantage (less copying -> less GC), and it usually only shows itself in "toy" examples rather than "real" backends. Those usually construct the list dynamically rather than refer to a fixed constant.

**Comment by dwang20151005** [comment]
>  if company inserts a part of a string returned in candidates (usually following the complete-common logic path), the prefix action, when called on new location, should return the old prefix with the new part appended. If the backend returns a different (probably much shorter) prefix, company considers this to be a failed completion.

Oh, I am breaking your rule. In my actual code, `prefix` returns only the current sexp atom as the string value. Once the user types `(` then `candidates` will suggest `'("foo" "fobar")`. Instead, company wants `candidates` to suggest `'("(foo" "(fobar")`.

Would this be a good mental model?

> If you take whatever `prefix` returns as the current token, company-mode expects that `candidates` will only suggest completions within the same token.

I am violating this expectation because some of my candidates have multiple tokens in them. Some of my tokens are too trivial to suggest on their own (`(`).  Which is fine: I'm doing something unusual.

Anyway, I worked around it by using `company-completion-started-hook` to record `(point)` when completion starts, so that `prefix` can keep returning a string that goes as far back as company-mode expects.

Thank you for your consistently quick and helpful responses.  And for company-mode!

**Comment by dgutov** [comment]
> Oh, I am breaking your rule

That's what I thought ;-)

> Instead, company wants candidates to suggest '("(foo" "(fobar").

You can adjust `candidates`, or the logic in `prefix`. But they should match, yes.

> Anyway, I worked around it by using company-completion-started-hook to record (point) when completion starts, so that prefix can keep returning a string that goes as far back as company-mode expects.

That's an unusual way to solve this, but it should work, too.

Cheers!
