### ISSUE TITLE
very noticeable input lag with company-capf + ccls or clangd

### ISSUE THREAD

**Issue by pushqrdx** [company-mode/company-mode#1073]
First thanks for company mode, it's awesome. but i have faced an inconvenience pretty much since my first attempts to switch from vim to emacs and that is popup completion menu cause an annoying input lag around 15~30ms, it becomes a little bit tolerable if i set `company-minimum-prefix-length` 2 instead of 1, however it's still there. This problem persisted since the days i tried with just emacs 26 to emacs 27 with jannson, and now i am 28 with jannson + native compilation but still something about company-capf increases input lag. I'd really appreciate and am willing to help finding a way to diagnose and maybe fix this issue.

**Comment by dgutov** [comment]
Hi! company doesn't have any support for ccls or clangd. You must be using lsp-mode or eglot.

If it's lsp-mode, there are recommendations here: https://emacs-lsp.github.io/lsp-mode/page/performance/

See especially the last section.

**Comment by dgutov** [comment]
How do you measure the input delay, BTW?

**Comment by pushqrdx** [comment]
> Hi! company doesn't have any support for ccls or clangd. You must be using lsp-mode or eglot.
> 
> If it's lsp-mode, there are recommendations here: https://emacs-lsp.github.io/lsp-mode/page/performance/
> 
> See especially the last section.

I know but lsp with these servers in vim have virtually no impact on input latency, also clang is pretty fast. I will give `(setq lsp-print-performance t)` a shot to see if bottleneck comes from lsp



> How do you measure the input delay, BTW?

I play instruments so i am used to give a pretty close approximation to latency especially +10ms, i'd love to know how can benchmark a company backend to confirm that though.

**Comment by dgutov** [comment]
> I know but lsp with these servers in vim have virtually no impact on input latency, also clang is pretty fast.

You can try writing some Emacs Lisp code for comparison, e.g. in `*scratch*`. That backend is not "free" either, but IME it's pretty fast. And it also goes through `company-capf`.

> I play instruments so i am used to give a pretty close approximation to latency especially +10ms, i'd love to know how can benchmark a company backend to confirm that though.

There have been a few articles on the subject, like https://pavelfatin.com/typing-with-pleasure/

I haven't done any of these experiments myself, though.

**Comment by pushqrdx** [comment]
@dgutov 
> You can try writing some Emacs Lisp code for comparison, e.g. in *scratch*. That backend is not "free" either, but IME it's pretty fast. And it also goes through company-capf.

strangely enough in scratch buffer it seems like company is very responsive, but with any lsp (eglot, nox, lsp-mode) input lag starts to appear which is very strange because in vim + lsp this doesn't happen (so it's not that my machine can't handle lsp). I have been trying to find out the reason this for the last few days, unfortunately with no luck. Do you have any more suggestions i'd really appreciate if we can figure this one out

> There have been a few articles on the subject, like https://pavelfatin.com/typing-with-pleasure/
nice article, and yes i can perceive input latency down to ~10ms mainly because i am used to play midi instruments which i think trained me for this.

**Comment by dgutov** [comment]
> I have been trying to find out the reason this for the last few days, unfortunately with no luck.

I don't use LSP with any regularity so far, so I don't have much experience to share. It must depend on the size of the project, though, and on the individual LSP server's behavior (whether it sends much bigger JSON documents than necessary, e.g. all completions instead of just ones that were requested).

IIUC both Vim and VS Code have an advantage in that they can parse JSON in the background (one using plugins written in foreign language with its runtime, another with Node's stdlib), whereas Emacs' single-threaded VM is limiting in this respect. There have been significant improvements made in JSON parsing speed in Emacs 27, but some configurations where it's still not enough probably exist.

The lsp-mode folks should give better advice than me, and there is some on the page I linked to. As well as the procedure for reporting performance problems. Even if you don't see anything out of the order in the profile you collected, maybe Ivan or others can.

> nice article, and yes i can perceive input latency down to ~10ms mainly because i am used to play midi instruments which i think trained me for this.

I meant to say that its method could be used to measure the latency of different command: just typing, typing with completion popup (elisp backend), typing with completion (lsp-mode). But since you only see high latency in the last case, following up with `lsp-mode` maintainers seems like the best choice.

**Comment by miguelmartin75** [comment]
Adding some additional context since I would love this issue resolved.

I'm not a developer for an LSP plugin - I've just noticed input lag with *slow* LSP servers (it can get to the point where it blocks the UI) - I don't really have a choice in this unfortunately.

Feel free to correct me if I'm wrong on any of these points as I'm pretty new to emacs.

>IIUC both Vim and VS Code have an advantage in that they can parse JSON in the background (one using plugins written in foreign language with its runtime, another with Node's stdlib), whereas Emacs' single-threaded VM is limiting in this respect. There have been significant improvements made in JSON parsing speed in Emacs 27, but some configurations where it's still not enough probably exist.

[async json parsing](https://github.com/emacs-mirror/emacs/blob/master/lisp/jsonrpc.el#L227) (on a second look - perhaps this is just the requesting and not actually parsing) is possible in emacs. Though I know you can have async processes, so I think theoretically parsing JSON asynchronously in emacs should be possible.

I believe both eglot and lsp-mode handle the requests/json parsing asynchronously. 

For eglot it's a bit easier to see how it works since it's a pretty minimal implementation of an LSP client. It does uses `jsonrpc-async-request` for some parts, e.g. [for signature docs](https://github.com/joaotavora/eglot/blob/master/eglot.el#L2382)

But, interestingly eglot doesn't use the async form of jsonrpc-request for it's [completion-at-point function](https://github.com/joaotavora/eglot/blob/master/eglot.el#L2164) - which I believe is what company-mode calls if you're using `company-capf` (tbh - I'm basing this off the callstack from `M-x debug-on-entry` for company-complete, since I'm really not familiar with how company-mode works)

From what I can tell, in order to add async completions to eglot-mode we'd probably need to write a custom backend similar to [company-irony](https://github.com/Sarcasm/company-irony/blob/master/company-irony.el#L79) (since this seems to be an async backend - I found this from #325) with some modifications to eglot - I assume. 

I'm not sure what the situation is for `lsp-mode` but I would imagine it's similar.

---

Additionally, I am a vim convert (I still use vim tbh). If we compare this to deoplete or ncm2 (two popular async completion plugins), the way they allow a backend to (asynchronously) send new data whilst the user is performing a completion. Obviously this can go wrong if a user is currently selecting a completion. This is probably why there is no input lag as @pushqrdx notices.

To be honest, at first I didn't think company-mode had support for async backends as I can't find any documentation on async backends or how this works with company-mode (please update docs). How does it compare to what I described above for vim?

**Comment by dgutov** [comment]
> (on a second look - perhaps this is just the requesting and not actually parsing)

Indeed. Parsing must be done on the main thread because that's where all object allocations are required to be. At least, for now.

> I think theoretically parsing JSON asynchronously in emacs should be possible (at least for the context of displaying completions)

Asynchronously - yes, though not concurrently.

> But, interestingly eglot doesn't use the async form of jsonrpc-request for it's completion-at-point function - which I believe is what company-mode calls if you're using company-capf

That is true: it uses a somewhat peculiar approach where it emulates a synchronous completion function, but one that aborts its processing as soon as it detects any new input from the user. That is a necessity for it, since `completion-at-point-functions` has no officially supported async convention. In theory, it should yield the same responsiveness benefits as "proper" async conventions, but I suppose some extra latency due to how `accept-process-output` works might have crept in.

I haven't looked into it personally, though. `eglot` or `lsp-mode` developers (the latter uses a similar scheme UUIC) should be better equipped to help with debugging and benchmarking here.

> in order to add async completions to eglot-mode we'd probably need to write a custom backend similar to company-irony

If you have time, maybe try doing it and then compare the latency. The documentation for the async convention is inside the `company-backends` docstring.

> If we compare this to deoplete or ncm2 (two popular async completion plugins), the way they work (at a high-level from my observations) is they allow a backend to (asynchronously) send new data whilst the user is performing a completion.

How does it look to the user? The popup list updates mid-display? While the user is looking at it?

Company's native async convention is simpler: the backend is allowed to trigger the callback once, with all completions that it has found. The main goal of this approach is to avoid stuttering while the user is typing, if they type faster than the backend can compute completions. When the user wants to use one of the completions explicitly, though, they have to wait to the server to send them, right?

**Comment by dgutov** [comment]
Hey all, https://github.com/emacs-lsp/lsp-mode/issues/2758 is talking about this issue, with a potential fix.

**Comment by dgutov** [comment]
It turns out that, in the interest of non-blinking visuals we've inhibited some occurrences of redisplay where it would have occurred naturally.

Some of that was (and remains) good, but overall the effect was that, when the backend is asynchronous and relatively slow to respond, we usually waited for the next keystroke before displaying the current one as having been typed. That should have had very little impact on on practical matters (we're waiting for completions either way), but apparently created an unsettling visual effect where you're typing, but nothing "comes out".

This should be fixed now, with a strategic redisplay and re-rendering of the necessary visualizations in the middle of fetching completions, using a timer. You can tweak its delay time with var `company-async-redisplay-delay`. The default makes it happen very quickly, which might be unnecessary if your LSP backend is very fast (double redisplay is not exactly "free").

Anyway, please try it out in the new version.

**Comment by pushqrdx** [comment]
@dgutov sorry for delayed response, i just tested latest clangd with company mode and indeed i can't notice any lag now, it was exactly what you described in the comment above

**Comment by bmourad01** [comment]
Sorry to beat the dead horse, but I'm using `lsp-mode` for writihg OCaml code and I'm noticing that with `company-capf` in the available backends, it will block emacs while waiting for completions. When I remove it from the backends, the problem goes away. Is there any good way to fix this? I'm having trouble with automatically removing `company-capf` from the backends every time I open a file.

**Comment by pushqrdx** [comment]
@bmourad01 I guess removing `company-capf` isn't even an option because you'll lose lsp completions that way, I also noticed that the input lag issue has returned, it isn't as prominent as before but its back I was planning on reopning an issue for it but wasn't sure if it was only me

**Comment by dgutov** [comment]
When did it return?

There haven't been many significant changes in `company-mode` lately. Perhaps it's a good idea to look at recent updates in `lsp-mode`.

**Comment by pushqrdx** [comment]
@dgutov i can't pin point when exactly because i was away for quite some time now, but on latest everything (incl Emacs 29), input lag is back, it is even more apparent in elisp files, which i believe don't use lsp-mode

**Comment by bmourad01** [comment]
Removing it didn't affect completions for me (I still use `company-lsp` even though it's deprecated, simply because it does not block).

**Comment by dgutov** [comment]
That really shouldn't happen. We might have different tolerance toward Emacs's interactivity delays, but I really don't see any significant input lag.

You might have to bisect your configuration starting with `emacs -Q`. Or otherwise produce a reproduction scenario starting with it.

If @pushqrdx and @bmourad01 you both are using something like Doom, then it could be caused by some latest changes in there, IDK.

**Comment by pushqrdx** [comment]
@dgutov I always use vanilla emacs, company is one of the few plugins I have, in fact I remember running profiler to see what was using most of the processing time and it was `company-calculate-candidates` which for some reason started interfering with user input again, the lag is most noticeable in elisp mode, probably because there're too many candidates? anyway it's something like 20~40ms

**Comment by dgutov** [comment]
Okay, in that case, something might have started taking more time. If you want to run the profiler again, `M-x profiler-start` is a good place to, ahem, start.

20-40ms is not a delay people tend to notice, though (the threshold is usually around 100 ms), so unless both of you play instruments, you might be seeing different issues.

**Comment by dgutov** [comment]
And after you call `M-x profiler-report`, you can expand the different items to see the specific functions which take more time. The specific backend and the functions it calls, for instance.

You can copy it here too.
