### ISSUE TITLE
Is it possible to show the first candidate inline?

### ISSUE THREAD

**Issue by si14** [company-mode/company-mode#123]
Here is an example from `auto-complete`:

![autocomplete](https://cloud.githubusercontent.com/assets/316910/3124412/cbc934a6-e77c-11e3-8b03-d84c20cec094.png)

I like AC's "show first candidate immediately and then the list" logic a lot. It would be awesome to replicate this behavior with `company-mode`.

**Comment by kencoken** [comment]
> * If you explicitly want to show the list on a timer but after a delay, someone will have to write a wrapper for `company-pseudo-tooltip-unless-just-one-frontend`

I've now done this in my own branch of company-mode:

https://github.com/kencoken/company-mode/commit/bbbf217643b84471125ddfa7bdc98632656daa4f

This allows an additional delay before showing a tooltip by doing the following:

* set the new `company-idle-delay-tooltip` variable to the desired additional delay
* replace `company-pseudo-tooltip-unless-just-one-frontend` in the frontends list with `company-pseudo-tooltip-unless-just-one-frontend-delay`

Popups then appear `company-idle-delay-tooltip` seconds after the new frontend is triggered (and the inline completion can be set to occur immediately by setting `company-idle-delay` to 0 as normal).

@dgutov – let me know if you think these changes would be useful upstream, as would be happy to issue a PR.

**Comment by dgutov** [comment]
@kencoken Sure, I think this will be useful. Quite a few people asked, after all.

Depending on the size of the resulting patch, you might have to sign the copyright assignment papers first.

But I think we can simplify the solution a bit. Since you're not publishing it separately, maybe adding a new frontend is not necessary: the "tooltip idle delay" will simply control whether the pseudo-tooltip is only displayed only after a delay. This will slightly complicate the `run-with-timer` call, I imagine.

Some renaming suggestions:

`company-idle-delay-tooltip` -> `company-tooltip-idle-delay` or `company-tooltip-extra-delay`.
`company-timer-tooltip-delay` -> `company-tooltip-timer` or `company-tooltip-delay-timer`.

**Comment by dgutov** [comment]
Also: I think you can cancel the new timer in the `pre-command` handler of the frontend, can't you?
