### ISSUE TITLE
Fuzzy issue in company-preview-frontend

### ISSUE THREAD

**Issue by ramblehead** [company-mode/company-mode#1241]
## The Bug

In my settings I have ```company-preview-frontend``` enabled and use multiple back-ends. In this post ```lsp-mode``` and ```tide-mode``` are used for the issue description.

With ```tide-mode``` back-end, company completion looks like the following:
![Screenshot from 2021-10-21 15-17-47](https://user-images.githubusercontent.com/2130398/138296526-3b965639-51d4-4fa3-90bf-dbc8814a8fd8.png)

The ```lsp-mode``` has recently (not sure exactly when) started doing "fuzzy" completions (at least in ```ts-ls```) and that broke ```company-preview-frontend``` (notice "cons" prefix repetition in "console" word completion):
![Screenshot from 2021-10-21 15-22-41](https://user-images.githubusercontent.com/2130398/138297537-e29285a6-cf4c-4868-a5f1-c2477759300e.png)

## The Cause

The entry-point for company-preview is ```company-preview-show-at-point()``` function. This function has the following statement:

```elisp
(setq completion
      (if company-common
          (company-strip-prefix completion)
        completion))
```
The above statement works well with conventional completion with no fuzzy logic (as in tide-mode screenshot above). However, with fuzzy completion it fails to do ```company-strip-prefix()``` as ```company-common``` is ```nil```.

```company-common``` is updated in ```company-update-candidates()``` function with the following statement:

```elisp
(setq company-common
      (if (cdr company-candidates)
          (let ((common (try-completion "" company-candidates)))
            (when (string-prefix-p company-prefix common
                                   completion-ignore-case)
              common))
        (car company-candidates)))
```

With fuzzy logic ```(try-completion "" company-candidates)``` returns empty string as fuzzy candidates have no common sub-strings. Thus, company-preview shows the full ```completion``` with no common prefix stripped.

## A Solution

To solve Subj., I would like to suggest to modify ```setq completion``` statement in ```company-preview-show-at-point()``` as the following:

```elisp
(setq completion
      (if company-common
          (company-strip-prefix completion)
        (if (cdr common)
            completion
          (let* ((first-common-range (car common))
                 (first-common (and first-common-range
                                    (substring completion
                                               (car first-common-range)
                                               (cdr first-common-range)))))
            (if (and first-common
                     (eq (car first-common-range) 0))
                (substring completion (length first-common))
              completion)))))
```

In this ```setq completion``` version, if ```company-common``` is not ```nil```, it is used to strip prefix as in the original version. If ```company-common``` is ```nil```, then we check if ```common``` has only one range - ```(beg . end)``` - and ```beg``` is ```0```, i.e. pointing to the beginning of ```completion``` string. Then, if true, we use ```common``` as the prefix to strip, otherwise use full ```completion```.

The following screenshot is what we have with the above ```setq completion``` modification in ```company-preview-show-at-point()```:
![Screenshot from 2021-10-21 15-55-16](https://user-images.githubusercontent.com/2130398/138304039-49fd28b1-6bab-4f14-bc14-e8009a04eba9.png)

This screenshot is showing what happens with conventional completions in presence of fuzzy candidates - it should cover 99% of use cases (in my typing at least :). Fuzzy candidates are then completed as the following:

![Screenshot from 2021-10-21 15-59-47](https://user-images.githubusercontent.com/2130398/138304581-3eb614cc-ab56-48e8-ae8f-c2eaf8cab1ee.png)

![Screenshot from 2021-10-21 16-00-24](https://user-images.githubusercontent.com/2130398/138304736-2ab3bcd2-e779-42c0-ae4f-47ec32c01aef.png)

Apologies for the long description - the issue is a bit complected. I hope it can be fixed upstream either with my or some other solution.

Thank you for the excellent emacs completion package!

**Comment by rdiaz02** [comment]
I am aware the bug has been closed. I stumbled upon this, however, when trying to understand why company seemed to do "fuzzy" matching with LSP but not otherwise (and I was reassured it was not just me when I read this:)

> The `lsp-mode` has recently (not sure exactly when) started doing "fuzzy" completions (at least in `ts-ls`) 

I do not like this "fuzzy" matching in many cases. As per https://github.com/emacs-lsp/lsp-mode/issues/2563#issuecomment-767987191 one can try to disable it with:

```
(advice-add #'lsp-completion--regex-fuz :override #'identity)
```

**Comment by dgutov** [comment]
Basically, it's up to the each backend whether to do fuzzy matching. Could be a little confusing (sorry), but it's hard to do otherwise without adding unnecessary performance overhead.

Regarding fuzziness in LSP, I suppose it depends on how well the matching and sorting in each specific language server. Personally, I like the overall idea, but it could be too much for some environments.

**Comment by rdiaz02** [comment]
Thanks!  

Sorry if I was confusing. I looked into company's issues to see if someone had mentioned LSP's fuzziness; I was trying to disable LSP's fuzziness in company, not right now because of performance, but because I found it too much (many matches that are not relevant at all), for example with LaTeX references. And I wasn't sure if it was me unintentionally doing something I shouldn't. I found this report, and though the bug is solved, it made it clear that fuzziness is something that LSP does. 

And then I found the entry that explains how one can try to disable LSPs fuzziness, and I figured someone else might stumble upon this issue with a similar concern.
