### ISSUE TITLE
Certain overlays cause completion menu to be displayed incorrectly

### ISSUE THREAD

**Issue by qaiviq** [company-mode/company-mode#1269]
## Description
Certain overlays/text properties (notably `before/after-string` for overlays and the `string` display property for text) can cause a single line of text to be displayed as multiple lines. Whenever there is such an overlay above the cursor in the current window, the company completion menu shows up in the wrong spot. 

## Steps to reproduce
- Open a new emacs session without any configuration:
  `emacs -nw -q`

- Navigate to the scratch buffer

- Add such an overlay by evaluating:
  `M-:` `(overlay-put (make-overlay 1 1) 'before-string "Multiple\nLines\nDisplayed\nBy\nThis\nOverlay\n")`

- Add a bunch of newlines at the end of the file, since the bug does not seem to occur when you are already on the last line:
  `M-:` `(progn (end-of-buffer) (dotimes (i 10) (newline) (previous-line)))`

- Enable company mode:
  `M-:` `(progn (package-initialize) (require 'company) (company-mode))`

- Insert the start of a variable or function for company to complete

## Screenshots
![CompanyBug](https://user-images.githubusercontent.com/65581045/143781664-8954dfed-598c-49c4-be84-d56cdb513729.png)

**Comment by dgutov** [comment]
Hi!

Since the completion overlay is rendered using the `before-string` overlay property, any additional such properties/overlays can naturally conflict with how it looks. I don't think there is a universal solution, aside from working around/disabling/plugging into well-known packages that can do so. Is there a particular package you use which creates this incompatibility?

The alternative, of course, is to use a different popup, such as `company-posframe` or `company-box`.

**Comment by qaiviq** [comment]
Hi, thanks for the quick response!

I am not aware of whether it is a problem with any existing packages, but I ran into the issue while developing one of my own. Since the company overlay and the other overlay are separate, I don't think it directly interferes with the completion overlay, it just causes a miscalculation as to which line the completion overlay should be displayed on.

It seems that both `company-posframe` and `company-box` do not have this issue, though, so I will try using those. Thank you for bringing my attention to them.
