### ISSUE TITLE
dropdown buffer is often mangled in org mode

### ISSUE THREAD

**Issue by JonatanSahar** [company-mode/company-mode#1347]
Hi,
I often get a situation like the following:

![image](https://user-images.githubusercontent.com/18332012/196954954-a62ccb00-ed94-4f98-b966-fee124546fb9.png)

I've found another issue where it said this was relatedto different fonts being used in the buffer. In my case text is displayed using the same font (although with different face attributes).

Is there any wasy to resolve this?
Thanks!
#### Output of the command `M-x company-diag`
```
Emacs 27.1 (x86_64-w64-mingw32) of 2020-08-21 on CIRROCUMULUS
Company 0.9.13

company-backends: (company-capf
 (:separate company-dabbrev company-yasnippet company-ispell))

Used backend: (:separate company-dabbrev company-yasnippet company-ispell)

Major mode: org-mode
Prefix: "res"
Completions:
  "respond"
  "response"
  "results"

**Comment by dgutov** [comment]
The Org buffers are often rife with advanced display engine tricks. And, of course, the popup is oriented at the monospaced buffers, otherwise it has no chance of lining up.

There are alternative frontends you can use, based on child frames:

https://github.com/tumashu/company-posframe/
or
https://github.com/sebastiencs/company-box/

I suppose we should mention these somewhere in the wiki.

**Comment by dgutov** [comment]
If you have the time, I'm curious how it looks for you with this branch: https://github.com/company-mode/company-mode/pull/1394

**Comment by dgutov** [comment]
Try this again when you have the time. Now in MELPA.

**Comment by JonatanSahar** [comment]
Thanks! will do
