### ISSUE TITLE
Backend company-files reports invalid function error

### ISSUE THREAD

**Issue by mikaelspringer** [company-mode/company-mode#1385]
#### Output of the command `M-x company-diag`
helm-M-x-execute-command: Company: backend company-files error "Invalid function: ("\"\\(\\(?:\\.\\{1,2\\}/\\|~/\\|/\\)[^\"
]*\\)" "'\\(\\(?:\\.\\{1,2\\}/\\|~/\\|/\\)[^'
]*\\)" "\\(?:[ 	=[]\\|^\\)\\(\\(?:\\.\\{1,2\\}/\\|~/\\|/\\)[^ 	
]*\\)")" with args (prefix)

#### Describe the issue
I get the following error message continuously when editing in Emacs (in echo area and *Messages* buffer:
Company: An error occurred in auto-begin
Company: backend company-files error "Invalid function: ("\"\\(\\(?:\\.\\{1,2\\}/\\|~/\\|/\\)[^\"
]*\\)" "'\\(\\(?:\\.\\{1,2\\}/\\|~/\\|/\\)[^'
]*\\)" "\\(?:[ 	=[]\\|^\\)\\(\\(?:\\.\\{1,2\\}/\\|~/\\|/\\)[^ 	
]*\\)")" with args (prefix)

#### Steps to reproduce
- Edit any file in Emacs.

#### Expected behavior
No errors.

#### The error backtrace
Emacs crashes if I enable debug on errors, followed by editing a file in Emacs. I cannot therefore supply a backtrace.

**Comment by dgutov** [comment]
Hi!

Check out this thread: https://github.com/company-mode/company-mode/issues/1381#issuecomment-1501170400

**Comment by Jdogzz** [comment]
Unfortunately it appears the problem, or at least a similar one, is still present. Perhaps that is because it is on an even more recent build than mentioned in the thread @dgutov linked to above? Reading through that thread, I see a mention of testing emacs 30 in one comment here:

https://github.com/company-mode/company-mode/issues/1381#issuecomment-1499533707

But after that, I see no mention of trying the git version of emacs nor testing emacs 30.

I can reproduce the following error on Ubuntu 23.04 VM as a clean test environment. Essentially, all that's going on is I install straight, then use-package, then company, and that's it. For the record, company is but one of several packages that are throwing errors upon calling them with use-package, and it appears to be a common theme that the ones involving modes are the ones giving me issues.

Steps to reproduce:

1. Compile emacs from git.
Version: GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0) of 2023-04-28
Git hash: 5c0f0751d0541bbdf0696ef3e76e2ad6562adcb9

2. Add these two initialization files:

`early-init.el`
```
(setq package-enable-at-startup nil)
```

`init.el`
```
(toggle-debug-on-error)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default 1)
(straight-use-package 'use-package)

(use-package company
	:config (
	(global-company-mode)
	)
	)
```

3. Open emacs.

Here is the backtrace:
```
Debugger entered--Lisp error: (invalid-function (global-company-mode))
  ((global-company-mode))
  (progn ((global-company-mode)) t)
  (condition-case err (progn ((global-company-mode)) t) ((debug error) (funcall use-package--warning0 :config err)))
  (if (not (require 'company nil t)) (display-warning 'use-package (format "Cannot load %s" 'company) :error) (condition-case err (progn ((global-company-mode)) t) ((debug error) (funcall use-package--warning0 :config err))))
  (condition-case err (if (not (require 'company nil t)) (display-warning 'use-package (format "Cannot load %s" 'company) :error) (condition-case err (progn ((global-company-mode)) t) ((debug error) (funcall use-package--warning0 :config err)))) ((debug error) (funcall use-package--warning0 :catch err)))
  eval-buffer(#<buffer  *load*> nil "/home/test/.emacs.d/init.el" nil t)  ; Reading at buffer position 663
  load-with-code-conversion("/home/test/.emacs.d/init.el" "/home/test/.emacs.d/init.el" t t)
  load("/home/test/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x17600777677e015f>) #f(compiled-function () #<bytecode -0x1f3c61addc0b4d35>) t)
  command-line()
  normal-top-level()
```

**Comment by dgutov** [comment]
Erm, this particular config is incorrect (not valid Lisp form):

```el
(use-package company
	:config (
	(global-company-mode)
	)
	)
```

It should be either

```el
(use-package company
	:config (progn
	(global-company-mode)
	)
	)
```

or just

```el
(use-package company
	:config (global-company-mode)
	)
```

**Comment by Jdogzz** [comment]
Thanks for the pointer, I hadn't realized the syntax was incorrect. Making the fixes you shared fixed my problem, thank you!
