### ISSUE TITLE
Overload screenshot

### ISSUE THREAD

**Issue by nosami** [company-mode/company-mode#269]
I was just wondering if you have a screenshot of the how the overload resolution is working before I try and implement it for C#.

If you don't, just close.. thanks!

**Comment by dgutov** [comment]
You mean, to reassure you that it works at all?

Please clarify what you want to see, though. Isn't this an example of a popup with overloads?

https://raw.githubusercontent.com/OmniSharp/omnisharp-emacs/master/pics/company-mode-doc-buffer.png

**Comment by nosami** [comment]
Ah, ok..... we have that already... I was hoping that there was something like this (but text based of course). Thanks!

![pic](https://jabbrlive.blob.core.windows.net/jabbr-uploads/clipboard_c44e.png)

**Comment by dgutov** [comment]
Nope, that's the best we can do now.

Collapsing overloads in the popup and moving their info to a separate display area would require a somewhat different data model, I think. And we also don't have a doc popup.

But hey, if you think it will be generally applicable, feel free to open an issue.

**Comment by nosami** [comment]
company-mode has been fine as it is for me until recently. 

It was pointed out that I need to support targeting multiple frameworks where some completions are not available for certain frameworks but are for others.

The only way that I can think of doing this (with just one list) is by duplicating each completion where they don't exist for all frameworks and displaying some extra information to inform the user. This is going to clutter the dropdown considerably.

I think that I might be able to replicate something that works like my screenshot without you changing the company-mode code though. In my screenshot above, I could display the first list, and after the user selects the method and then types the '(',  show a 2nd list with the overloads for that one method.

**Comment by dgutov** [comment]
> I need to support targeting multiple frameworks

Admittedly, I don't know all the details, but shouldn't you be able to detect which framework(s) is/are used exactly, during completion? I wouldn't like to see completions from irrelevant libs, even if they don't clutter the primary list.

> duplicating each completion where they don't exist for all frameworks and displaying some extra information to inform the user

If it's just about overloads, their info could be displayed after completion, in eldoc-mode fashion (so to speak), only instead of the mode-line, using the popup. [function-args](https://github.com/abo-abo/function-args/#fa-show) and [jedi.el](http://tkf.github.io/emacs-jedi/latest/#screenshots) have separate implementations of this. IIRC, this is also the approach used by MS Visual Studio (you would press up or down to switch between overloads and their descriptions).

> and after the user selects the method and then types the '(', show a 2nd list with the overloads for that one method

Maybe, just as long as it's not in the same completion action: currently, you can't initiate new completion in `post-completion`.

**Comment by nosami** [comment]
This is for people that need to support multiple frameworks with #ifdefs so
all information is relevant :(

I'll have a look at how jedi works on emacs... only tried that with vim so
far, thanks.

Yeah, I thought it could be done with a completely separate completion
action. I'll have to try it and see how it works out.

Thanks!

**Comment by nosami** [comment]
@dgutov I just saw this - https://github.com/abo-abo/function-args . The fa-show screenshot is kind of what I was hoping for.

**Comment by dgutov** [comment]
Yep. I linked to it (or at least tried to) in the third comment here.

It doesn't seem like a natural part of company-mode, though. Or at least I don't know how `company-backends` would have to be extended to accomodate it.
