### ISSUE TITLE
Completion list disappears, hiding buffer lines

### ISSUE THREAD

**Issue by morhekil** [company-mode/company-mode#278]
Hello,

I have a weird problem with a completion list displayed by company mode. In most cases it works just fine, but on some particular lines or places in the file - it disappears immediately after being displayed, and what's worse - it hides the lines of the file I'm editing, too. Here's a screencast to illustrate the problem:

![Screencast](http://f.falsum.me/image/0T3o2k3v0p3I/lines-02.gif)

I noticed this problem in different modes, so it doesn't seem to be mode-specific, but I'm not sure how to debug it further. Any ideas/suggestions would be much appreciated!

I'm using company-mode 20150112.1841 on emacs 24.4.1, on OSX in the terminal (iTerm 2).

**Comment by dgutov** [comment]
Hi! The basics of troubleshooting are here: https://www.gnu.org/software/emacs/manual/html_node/emacs/Understanding-Bug-Reporting.html Starting with `emacs -Q` is a good approach when debugging after you try the first few obvious solutions anyway.

If the problem is stable and only depends on the file contents and your position, and persists across Emacs restarts, the victory is already in sight.

First, establish what parts of your Emacs configuration are responsible for this. The screencast seems to indicate that some linter is doing that (Flymake or Flycheck, or something similar). So, try starting with 

```sh
HOME=/tmp emacs
```

then install `company` and that other package in the brand-new Emacs, and open the file with the problem. If the bug is there, post the file here, as well as all everything I should know how to reproduce this. If the bug is not there, check your configuration, see if there are some settings for these two packages you can copy (test each of them), that make the bug appear. If it still doesn't appear, [bisect your configuration](http://stackoverflow.com/a/23772957/615245).

Then, if you've managed to reproduce the problem, but the file contains confidential information, feel free to send it to me privately, but better scrub out everything sensitive (and irrelevant, too) from the file, check that the bug is still reproducible, and post that version.

**Comment by morhekil** [comment]
Hi Dmitry,

thanks for that, it helped me to track down the issue. Apparently it is a compatibility problem with flycheck, and has already been reported to them (https://github.com/flycheck/flycheck/issues/526), and track to upstream's bug. There're some workarounds provided in that discussion, and apparently the fix is coming in 24.5, so the problem is resolved indeed in there. Thank you again for you help!

**Comment by dgutov** [comment]
Oh, right. I've already forgot about that issue. :)
