### ISSUE TITLE
Can't complete-common in template fields

### ISSUE THREAD

**Issue by hpdeifel** [company-mode/company-mode#281]
TAB in company-template-nav-map shadows the binding in company-active-map, so it's not possible to complete the common part of the candidates while there are still unvisited fields from a template expansion.

**Comment by dgutov** [comment]
Indeed, this can only be fixed when we set the current company keymap likewise from an overlay, because they always take precedence.

In the meantime, you should be able to write a command similar to [complete-or-indent](http://www.emacswiki.org/emacs/CompanyMode#toc9) and bind it in `company-template-nav-map`.
