### ISSUE TITLE
Support scrolling in the documentation buffer

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#309]
Hi,

`company--electric-commands` currently only contains `scroll-other-window` and `scroll-other-window-down`. Adding some support for `down-mouse-4` and `down-mouse-5` would be nice, as it would allow one to use their mouse to scroll in the documentation buffer (scrolling currently closes that buffer).

I tried adding these two commands to `company--electric-commands`, but they don't seem to make it through `key-bindings` as used on line 2032 of `company.el`. `read-event` returns

```
(down-mouse-4 (#<window 12 on *company-documentation*> 726 (229 . 284) 21980232 nil 726 (32 . 15) nil (5 . 1) (0 . 18)))
```

That would be really cool!

**Comment by dgutov** [comment]
Good idea. This should work now.

**Comment by cpitclaudel** [comment]
That's really cool, thanks

**Comment by cpitclaudel** [comment]
I wonder if this didn't go a bit to far, actually; the buffer doesn't seem to disappear anymore in some cases. I don't have a minimal example showing the problem, but the documentation buffer is not getting killed.

**Comment by cpitclaudel** [comment]
So the culprit is actually the commit just after that one. 

commit 448bcd8ebefb9f2a1e1db2986ec7b1c16edab0df
Author: Dmitry Gutov <dgutov@yandex.ru>
Date:   Tue Feb 24 22:39:51 2015 +0200
    company-show-doc-buffer: Bind other-window-scroll-buffer

**Comment by cpitclaudel** [comment]
Alright; the bug seems to be due to that commit taking the `let` out of the `company--electric-do` block. Putting it back fixes it. Was there a reason to move it out?

**Comment by dgutov** [comment]
> the buffer doesn't seem to disappear anymore in some cases

I don't see that, at least not in `emacs-lisp-mode`. Could it be that your `doc-buffer` implementation changes the window configuration? WRT to this kind of misbehavior, I guess the patch took a step back, yes.

> but the documentation buffer is not getting killed.

It should be buried, not killed.

> Was there a reason to move it out?

The idea was to create a local binding for `other-window-scroll-buffer` for the whole duration of `company--electric-do`, so that if the doc-buffer is opened in a window other that the "other window" (for instance, because it's displayed in one of the windows already), the scrolling commands still work on its window. And it's non-trivial to bind the `other-window-scroll-buffer` around the electric block, but call `doc-buffer` inside that block.

Maybe I've been solving a problem nobody's had before, that's what too much experimentation can do to you.

**Comment by cpitclaudel** [comment]
Thanks for the pointers. I tracked down the problem. 

In my function for `doc-buffer` I had `(display-buffer (current-buffer) t)`. I was using this to get the width of the window that I was printing the documentation in, in order to be able to center the text on the header line of the documentation, but that caused the buffer to not get unburied. Removing it solves the problem in one case, but not in all.

The major mode for which I'm writing a backend works with a fixed three-windows layout, and I need to print the documentation in one of these three windows. Thus, I use `(set-window-buffer window doc-buffer)` before returning the buffer to company. This used to work, but now it makes the buffer stick there instead of being buried. 

I can't really think of a workaround; is there a way to influence which window is chosen by company to display the buffer in? It seems to just be calling `(display-buffer (current-buffer) t)`, and I'm not aware of a robust way to influence the choice made by that function.

**Comment by cpitclaudel** [comment]
Addendum to my previous post: there's actually a pretty robust way of selecting that window, without bothering company:

```
(add-to-list 'display-buffer-alist (cons #'test-function
                                         (cons #'display-function nil)))
```

`test-function` checks whether the buffer is the documentation buffer, and `display-function` displays it in the right window.

This seems to work nicely. Do you see downsides to this approach?

**Comment by dgutov** [comment]
It should work fine, but it's a bit of disproportionate solution to the problem in question, I'd say. And I don't know if I want any of the code I run to silently modify `display-buffer-alist` (and keep the modification indefinitely).

Since you modify the window configuration in the `doc-buffer` intentionally (I didn't expect that), we can try harder and preserve the previous behavior. Maybe some other backends do that too.

I've pushed a new commit, please see if it causes any new problems.

**Comment by cpitclaudel** [comment]
That seems to fix it. So would you advise avoiding altering `display-buffer-alist` entirely? Couldn't it simply be made buffer-local? I thought it looked rather clean.

Anyhow thanks for the fix!

**Comment by dgutov** [comment]
Buffer-local is better, but the effect will still live beyond the execution of the current command.

You can bind it locally, but that wouldn't have helped here. Leaving behind an entry that would never be deleted is pretty dirty, even if you can anticipate every situation where it would come into play in the future. But TBH that's more a matter of aesthetics than anything else.

**Comment by cpitclaudel** [comment]
Thanks for the advice! I've reverting to simply selecting the right window. This seems to work great with the latest commits.

I also came across another case where explicit selection of the window is useful: to render html documentation backends can call `shr-insert-document`, and this needs the width of the window to page things properly.

**Comment by dgutov** [comment]
Okay, that sounds useful.

**Comment by oracleyue** [comment]
@dgutov Interesting I finally got to know use my mouse to scroll the help doc. Question: what's the keybindings (or function that I can bind one) to scroll the help doc (the one that opened by <f1>)? Many thanks!
