### ISSUE TITLE
Idle delay per backend

### ISSUE THREAD

**Issue by tuhdo** [company-mode/company-mode#326]
It would be nice if company has idle delay per backend, so we can use very small values for fast backends (i.e. 0.0) and large values for slow backends (i.e. the backend that communicate with external process).

**Comment by dgutov** [comment]
Yeah, that's doable. I guess we could even ask the backend which idle delay it prefers at a given time, in the given context, but I'd have to think about the implications more.

**Comment by dgutov** [comment]
Thinking about it more, that would require a certain change. Currently, we only call the backends with `prefix` only after `company-idle-delay` has passed. We'd have to change that and call `prefix` immediately in `post-command-hook`. That *probably* won't make the user experience worse since that handler is supposed to be fast, but not every backend author is necessarily careful that that.

For now, I think the easiest solution is for you to add some function to `company-completion-started-hook` that will change the local `company-idle-delay` value depending on the current value of `company-backend`. The main drawback is the effect will always be lagging by one command.

**Comment by codygman** [comment]
Is there any workaround for this in the meantime?

I'm loving a very low idle delay for writing which uses fast backends, but a delay of 0.01 just doesn't work very well for lsp backends like haskell-language-server.

I'm just switching my idle delay manually now, but that's not very nice. I guess I can probably use directory local variables in the meantime, but I haven't tried yet.

**Comment by dgutov** [comment]
You can set a different value of `company-idle-delay` in `haskell-mode-hook`?

**Comment by codygman** [comment]
> You can set a different value of `company-idle-delay` in `haskell-mode-hook`?

I'll try that tomorrow.

 My concern though is that value is global and that means if I set it as 0.5 delay in Haskell mode hook then it will also be 0.5 when I switch to an org buffer rather than the 0.01 delay I desire for org mode buffers.

**Comment by dgutov** [comment]
@codygman You can use `make-local-variable` to create buffer-local values of this variable.

**Comment by dgutov** [comment]
Yeah, I think just using local value of `company-idle-delay` in certain buffers is the way to go.
