### ISSUE TITLE
How to perform completion by inserting text at a specific offset rather than replacing the prefix?

### ISSUE THREAD

**Issue by abingham** [company-mode/company-mode#335]
Apropos to [this issue on emacs-ycmd](https://github.com/abingham/emacs-ycmd/issues/162), I'm trying to bridge a mismatch between company and ycmd do completion. Company has a notion of prefixes, and replacing the prefix text with candidates is how it does completion. Ycmd, on the other hand, doesn't broker in prefixes; it just gives me a list of candidates and the column offsets at which they should be inserted. So unless ycmd and company agree on where candidates should start (which they often do), I get bad behavior.

For example, if I'm completing `cd ~/sa`, I might calculate a prefix of `~/sa` by using `company-grab-symbol`. ycmd, however, will reply with candidates like `sandbox` and `sauropod`, i.e. without the leading `~/`. Since ycmd isn't communicating in terms of prefixes, I have to hope that these two different notions of "where the completion goes" agree.

What I was wondering is if there's a way to tell company to insert a candidate at a specific location irrespective of prefixes. I think I can *almost* use `match` to manage this, but I can't connect all of the dots (or it's impossible.) Do you have any ideas? I feel like I'm missing something simple here.

**Comment by dgutov** [comment]
I think you have to fixup each completion string, using the information at hand. See which column the prefix starts at, and if it's less that the column returned to you by ycmd, prepend the appropriate substring of prefix to each completion. If it's bigger than the column returned by ycmd, well, it's a problem, but there's nothing you can do except to cut off `(- prefix-col ycmd-col)` characters from the beginning of each completion. This might discard some information, but hopefully not.

Overall, it might give you a certain performance hit. Let me know if/when it becomes an annoyance.

`match` does not fit this use case: it's just about what's displayed in the popup. `completion-at-point-functions` also has a concept of "boundaries" (see the function `completion-boundaries`), which is somewhat related, but the completion function is expected to respond to `boundaries` before fetching completions, so that's not a good fit either, unfortunately.

Aside from the more complex shape of the return value, we could use a convention like this if we started with it originally (and didn't care about stuff like `company-minimum-prefix-length`, which takes effect, again, before fetching completions), but the current intention is to transition from `company-backends` to `completion-at-point-function`, and that API also determines the string-to-be-replaced on the client.

**Comment by dgutov** [comment]
I believe this is resolved.
