### ISSUE TITLE
compatibility issue with HideShow mode

### ISSUE THREAD

**Issue by runningskull** [company-mode/company-mode#417]
The company popup makes the hideshow line annotations disappear. (I notice the same thing happens with popup.el)

Screenshots:
- [before popup](http://f.cl.ly/items/3L1l1m1P2p2d1e2w3b3N/Screen%20Shot%202015-11-01%20at%207.13.07%20PM.png) (hideshow annotations are `...` at end of line)
- [after popup](http://cl.ly/image/0H2M043K1J3e/Screen%20Shot%202015-11-01%20at%207.14.20%20PM.png) (annotations are gone)

Emacs 24.5 (gui & terminal) // OSX 10.10 

Let me know if there's any other information I can provide that would be helpful. Thanks!

**Comment by dgutov** [comment]
This seems to be pretty much unavoidable with the current rendering method (we use an overlay with `display` property, the line annotations use overlays with a similar property; we're pretty much forced to override them).

On the other hand, if this issue is your biggest gripe with the popup display, I'd say we're in a good place.

**Comment by runningskull** [comment]
This still happens, but after using it for months in practice, it's not a problem. Closing this. Thanks for company-mode!
