### ISSUE TITLE
Misalignment issue with (mac-auto-operator-composition-mode) enabled.

### ISSUE THREAD

**Issue by jordwalke** [company-mode/company-mode#438]
![exported](https://cloud.githubusercontent.com/assets/977348/12002186/3de706ae-aaad-11e5-85de-d12fe4963b43.png)

When `(mac-auto-operator-composition-mode)` is enabled, single (typically wide) glyphs are rendered for two adjacent characters. Popular fonts take advantage of this (PragmataPro (pictured)) and Fira Code, among a growing list of others.

Company mode doesn't seem to render the right border of the dropdown list correctly with these fonts. The screenshot shows one example.

**Comment by dgutov** [comment]
Hi Jordan,

I think you should report this to the author of your Emacs distribution (Emacs Mac Port, right?), because these ligatures are rendered using the same font, right? That should mean that the width of the "combined" arrow should be equal to the width of the two original characters.

Whereas on this screenshot we see that the more ligatures a line has, the shorter is its width. Someone should correct me if it's working as intended, but in that case there's nothing we can do anyway: we render the popup using an overlay.

PS: You lucky bastard. The current GNU/Linux version of Emacs has no support for ligatures at all.

**Comment by jordwalke** [comment]
I'll file an issue on the mac port project -it seems that individual ligature glyphs are not rendered as a two character widths as the programming ligature fonts intended them to be. Yes, ligatures are truly awesome. On MacVim, everything works correctly and it is a joy. Hopefully, emacs (via the mac port) can get it to be the same level as MacVim.

**Comment by dgutov** [comment]
> I'll file an issue on the mac port project

You might have to use email instead, see the comments in https://github.com/railwaycat/emacs-mac-port/issues/95.

**Comment by jordwalke** [comment]
Thanks for the tip. It's a bit unfortunate as it will not be searchable in case others have the same problem, but I'll go ahead and send an email.

**Comment by cpitclaudel** [comment]
@dgutov Ligatures would definitely be cool. In the meantime, `prettify-symbols-mode` is pretty good :) Especially if you pair it with a properly monospacified font (I have some at https://github.com/cpitclaudel/monospacifier)

**Comment by dgutov** [comment]
@cpitclaudel `prettify-symbols-mode` is nice, but even if I just use the `lambda` -> `λ`, as soon as I write a lambda with arguments on multiple lines, they won't line up in the actual source code. Not too big a problem in Elisp, but it would come up more often when writing Ruby. I'm guessing monospacifier.py doesn't solve that.

But I'm glad you've solved the "math symbols break the popup" problem.
