### ISSUE TITLE
Completion needs an inferior Python process running

### ISSUE THREAD

**Issue by michaelsilver** [company-mode/company-mode#440]
When editing a python file, emacs complains "Completion needs an inferior Python process running":
<img width="742" alt="screen shot 2015-12-28 at 7 06 51 pm" src="https://cloud.githubusercontent.com/assets/5913522/12023922/9fc1463c-ad96-11e5-9ac2-8746ca30dad3.png">
I'm running GNU Emacs 24.5.1 (installed with Homebrew) and company-mode version 20151225.1910. I see this error was brought up in #377 and #84, but supposedly this was fixed already in Emacs 24.4? 

For reference, I'm using [graphene](https://github.com/rdallasgray/graphene) but the author [claims](https://github.com/rdallasgray/graphene/issues/30) it has nothing to do with graphene itself.

Any help would be appreciated. Thanks!

**Comment by dgutov** [comment]
Turns out, I was wrong: both 24.4 and 24.5 still contain the unfixed code. Sorry! I've edited the message in the other issue.

The recommendations in #377 should still apply: if you want completions from the built-in `python-mode`, you should launch an inferior Python process (`M-x run-python`). To use something more advanced, install e.g. `company-anaconda`.

If you only want "symbols from buffers" completions, however, or completions based on a tags file (backends `company-dabbrev-code` and `company-etags` respectively) that's a bit trickier: you'll need to add a function to `python-mode-hook` that either removes `company-capf` from `company-backends` locally, or removes `python-completion-at-point` from `completion-at-point-functions` (like in https://github.com/company-mode/company-mode/issues/189#issuecomment-56266891).

**Comment by michaelsilver** [comment]
Thank you for your quick response and help!
>The recommendations in #377 should still apply: if you want completions from the built-in python-mode, you should launch an inferior Python process (M-x run-python).

Indeed this does fix the issue. However, is there an automatic way to run python, so I don't have to `M-x run-python` all the time? I've already tried (separately):
```
(add-hook 'python-mode-hook 'run-python)
(add-hook 'emacs-startup-hook 'run-python)
(add-hook 'after-init-hook 'run-python)
```
But none of these do the trick.
>To use something more advanced, install e.g. company-anaconda.

Using `company-anaconda` does not appear to solve the problem. I followed their [installation and usage instructions](https://github.com/proofit404/company-anaconda#installation) but the same message ("Completion needs an inferior Python process running") still persists.

Alternatively, could you please tell me how I can disable `company-mode` only for python?

**Comment by dgutov** [comment]
> is there an automatic way to run python, so I don't have to M-x run-python all the time?

I wouldn't recommend this. You only need to launch it once per session, is that really a problem?

> Using company-anaconda does not appear to solve the problem.

Ah, you might have to combine that with the other suggestions anyway, because `company-anaconda` only provides completion when supposed to (outside of strings and comments, and only at the end of symbols), and you're still getting the error in other contexts.

> Alternatively, could you please tell me how I can disable company-mode only for python?

Call `(company-mode -1)` in `python-mode-hook`?

**Comment by michaelsilver** [comment]
> You only need to launch it once per session, is that really a problem?

It is an inconvenience, especially since I tend to open and close emacs frequently. However, I can live with it.

> Call (company-mode -1) in python-mode-hook?

I tried `(add-hook 'python-mode-hook (company-mode -1))` and also `(add-hook 'python-mode-hook (company-mode 0))` but neither worked. Any other ideas?

Thank you again for your help. Feel free to close the issue since it's clear there is no issue with `company-mode` itself.

**Comment by dgutov** [comment]
The second argument to `add-hook` must be a function. Try `(lambda () (company-mode -1))`.

No problem.

**Comment by dgutov** [comment]
> it's clear there is no issue with company-mode itself

Actually, even though it's true, the problem has come up repeatedly, and it's still unfixed in the current Emacs release. So I've pushed a workaround now.

**Comment by stardiviner** [comment]
I have similar issue, anaconda-mode can work for me when I disable python-mode's capf.
```lisp
(add-hook 'python-mode-hook
                 '(lambda ()
                   (setq-local completion-at-point-functions nil)))
```
python-mode will set capf to `(python-completion-complete-at-point t)`.

**Comment by michaelsilver** [comment]
Thank you! Looks like be2f586fc09c98d19d1e7d6c5854a02ed6716650 on it's own does not fix the issue, but in combination with @stardiviner's snippet, I successfully no longer get "Completion needs an inferior Python process running".

**Comment by dgutov** [comment]
@stardiviner Please don't quote your lambdas.

@michaelsilver Thanks for checking, one problem indeed remained: the `completion-at-point-functions` element in question had a different name in Emacs 24 than it has now in 25. Should work now without the above snippet, too.

**Comment by michaelsilver** [comment]
@dgutov Awesome, 931e758 did the trick; @stardiviner's snippet no longer required. Thanks again!

**Comment by anarcat** [comment]
this also confused the hell out of me. i am running version `20160325.1650` and it still tells me python has stopped. it's a usability problem because i originally thought company wasn't actually being fired on `M-TAB` because just waiting for the timeout would actually auto-complete (there's elpy at play here as well).

**Comment by dgutov** [comment]
@anarcat Python "stopped"? Please file a proper bug report: what you are doing, and which error you are seeing.

**Comment by anarcat** [comment]
sorry, i meant to say that i was having similar problems as the original bug report here, but it turns out i had some sort of misconfiguration. nice folks from #emacs-elpy helped me out and everything works now.

the magic recipe, for me, was:

```
apt-get install python-jedi python3-jedi
```

and:

```
(when (require 'company nil t)
  (add-hook 'after-init-hook 'global-company-mode))
(when (require 'elpy nil t)
  (elpy-enable))
```

thanks!

**Comment by dgutov** [comment]
@anarcat Why the `(when (require...` conditions? These won't work for a significant portion of users.

**Comment by anarcat** [comment]
it's to make my configs survive missing modules without crashing.
