### ISSUE TITLE
How to auto convert "." to "->"

### ISSUE THREAD

**Issue by ailisp** [company-mode/company-mode#442]
If I use company-mode writing C/C++, and type a variable which is a pointer, then type ".", how to automatically convert it to "->"? (If this variable is an instance or struct variable, not pointer, then do not convert). And happy new year :-)

**Comment by dgutov** [comment]
I don't know if we should, for two reasons:

* That doesn't really mesh with the current model, where you can just insert a completion without triggering the `post-completion` action. And we can't replace `.` with `->` before the user picks a completion. There's also a problem with indicating that the replacement will happen. Do you know other editors that do that? How does it look?

* The implementation will basically come down to calling Clang a second time if we didn't get any completions the first time, and there's `.` before the cursor. Which will take twice the time, and this backend is already fairly slow, because it's implemented in the most simple way (using the `clang` program, and not `libclang`).

Happy new year to you too! :fireworks:

**Comment by ailisp** [comment]
Thank you! Yes, it will take a twice check and will also change the user's typing before completion. Can I modify the configuration of company so that when type `foo.` it also list completions for `foo->` below the completions for `foo.` at the same time, rather than a double check after `foo.` completions are empty. Then when do completion, replace `.` with `->`. This seems a solution to these two problems. As for other editors, in Qt Creator, when type `.`, it will be replaced with `->` automatically. I am a new user and have just used Emacs for a month, and sorry if this is hard to implement

**Comment by dgutov** [comment]
> As for other editors, in Qt Creator, when type ., it will be replaced with -> automatically.

Yes, I've tried it out, and it works rather snappily there. I'm afraid it won't work as well in `company-clang`, because it already takes ~600ms to simply scan all basic Qt dependencies to perform completion in a sample project generated by Qt Creator. And I think (?) we do need that information, because we can't always determine whether the variable is a pointer because of possibility of type aliases, or when the `auto` keyword is used.

**Comment by dgutov** [comment]
@Sarcasm Do you think Irony would be better positioned to handle this kind of feature?

**Comment by Sarcasm** [comment]
Yes I think so. It does not seem completion-related to me, It could be just some kind of "magical" dot.

**Comment by dgutov** [comment]
> It does not seem completion-related to me, It could be just some kind of "magical" dot.

Indeed. I also think it would be more natural to implement as a command, or in `post-self-insert-hook`.

Please clarify, are you interested in implementing this, or should the OP consider filing the feature request at rtags? IIU https://github.com/Sarcasm/irony-mode/issues/99#issuecomment-39763199 correctly, certain features are not a priority.

**Comment by Sarcasm** [comment]
I have no intent to work on it now, I would accept pull request on this subject howewer (contribution welcome). Either way, pinging the rtags folks may be a good idea.

**Comment by dgutov** [comment]
All right, thanks for the answer. I'm closing this.

@ailisp Please file a feature request at [rtags](https://github.com/Andersbakken/rtags/issues) and/or [irony-mode](https://github.com/Sarcasm/irony-mode/issues/). Both of them have a `company-mode` backend you can use, too.
