### ISSUE TITLE
Wrong backend with web-mode.el

### ISSUE THREAD

**Issue by ignativs-reilly** [company-mode/company-mode#446]
Company is not loading the nxml backend when I use web-mode.el:
```    
M-x: company-diag 
Used backend: (company-dabbrev :with company-yasnippet) 
```
I can't find how to force a specific backend with a particular mode.

**Comment by dgutov** [comment]
Some backends have customizable variables that define which major modes the backends words in. Some backends work in all major modes.

You can't use `company-nxml` with `web-mode` because it expects a particular major mode. But not only that: I think it wouldn't work anyway, because it relies on nXML's parser to return completions.

If you're using `web-mode`, try something else, like [company-web](https://github.com/osv/company-web).

**Comment by ignativs-reilly** [comment]
I have tried company-web and is the same. I can't load company-web-html backend, dabbrev is the default backend loaded. I've tried a lot of options but can't make it work.

**Comment by dgutov** [comment]
> I can't load company-web-html backend

If you've tried following the instructions in its README, and they don't work, you should open an issue in that project.

**Comment by ignativs-reilly** [comment]
Ok, I will. Thanks.
