### ISSUE TITLE
[feature request] Flex/Fuzzy matching

### ISSUE THREAD

**Issue by PythonNut** [company-mode/company-mode#47]
[`flx`](https://github.com/lewang/flx) is a very smart sublime-text like fuzzy/flex matching library. After using similar flex matching in Vim's [`YouCompleteMe`](https://github.com/Valloric/YouCompleteMe) I miss it in `emacs`. I would seriously recommend trying it out for a bit. It's amazing how much code you can generate with a few key strokes using these advanced algorithms.

    (kcdg<tab> eism<tab> "jj" ens<tab>)

Becomes

    (key-chord-define-global evil-insert-state-map "jj" evil-normal-state)

I already try to use `flx` for everything (minibuffer, hippie-expand etc.), and the only thing left is auto-completion. I can't get it to work myself because it's so complicated. I also have a [feature request](https://github.com/auto-complete/auto-complete/issues/273) for [`auto-complete-mode`](https://github.com/auto-complete/auto-complete), but they seem busy with their big 2.0 rewrite and it's no going anywhere.

By the way, thanks for `company-mode` it's very fast and gets out of my way. I think it's awesome!

Thanks,
PythonNut

**Comment by PythonNut** [comment]
>  >   Why not work on the interface first?

> You (or anyone else) are welcome to implement the relevant completion-styles-alist elements. Should be relatively easy.

That part [is now done](http://emacs.stackexchange.com/a/13508/2642), and in fact it doesn't require `flx`, because `completion-style` does not control sorting. 

The systems that control sorting in vanilla minibuffer completion don't seem to be used by company. How can we now add a custom sorting function?

**Comment by dgutov** [comment]
> How can we now add a custom sorting function?

Via `company-transformers`, for example. If you want it to apply to all backends.

**Comment by dgutov** [comment]
> The systems that control sorting in vanilla minibuffer completion

What are those, by the way?

**Comment by PythonNut** [comment]
@dgutov they're pretty ugly, and I admit, I still don't quite understand how they work. 

* Displayed completions are sorted in `minibuffer-completion-help`
* When cycling, sorting is defined in `completion-all-sorted-completions`

In both cases, the sorting comparison function is extracted from the completion metadata:
```emacs
(let* ((completion--metadata (buffer-substring-no-properties
                                            start (point))
                                           base-size md
                                           minibuffer-completion-table
                                           minibuffer-completion-predicate)
    (sort-fun (completion-metadata-get all-md 'cycle-sort-function)))
    ...)
```

And the metadata comes from `minibuffer-completion-table`.

**Comment by dgutov** [comment]
Oh right. `company-capf` supports `display-sort-function`, but it's defined for each completion function separately.

**Comment by PythonNut** [comment]
I'm having good success with:
```emacs
(setq company-flx-cache (flx-make-string-cache 'flx-get-heatmap-str))
(setq company-transformers
  (list
    (lambda (cands)
      (cl-sort (cl-subseq (cl-sort cands
                            #'<
                            :key #'length)
                 0
                 (min 100
                   (length cands)))
        #'>
        :key (lambda (cand)
               (or (car (flx-score cand
                          company-prefix
                          company-flx-cache))
                 0))))))
```
In general, I'll guess that you don't want an exhaustive list of candidates if you're using fuzzy matching as the candidates quickly descend into chaos as the `flx-scores` decrease. 

`100` yields near-instantaneous performance for me. Of course it is possible in theory for a good match that is very long to slip through sort and truncate, but it's not a problem because: 1. it's very rare, and 2. you can always just type another character to help narrow down the candidates.

**Comment by dgutov** [comment]
This looks good. `company` can't depend on `flx` though, so you can either publish it as a package, or put the function somewhere in the wiki maybe.

**Comment by PythonNut** [comment]
How will we reimplement `company-dabbrev`?

**Comment by dgutov** [comment]
It need some other work, but in the end it should become a `completion-at-point-functions` element as well.

**Comment by PythonNut** [comment]
>  It should become a completion-at-point-functions element as well.
Is that the plan for all of the backends?

**Comment by dgutov** [comment]
In the long run, yes.

**Comment by PythonNut** [comment]
If anyone wants to test, this should be a better transformer:
```emacs
(setq
    company-flx-cache (flx-make-string-cache 'flx-get-heatmap-str)
    company-transformers
    (list
      (lambda (cands)
        (let ((num-cands (length cands)))
          (mapcar #'car
            (cl-sort (mapcar
                       (lambda (cand)
                         (cons
                           cand
                           (or (car (flx-score cand
                                      company-prefix
                                      company-flx-cache))
                             0)))
                       (cl-subseq (cl-sort cands
                                    #'<
                                    :key #'length)
                         0
                         (min 500 num-cands)))
              #'>
              :key #'cdr)))))
```
It's a bit faster because it only calls `flx-score` once per candidate, and it also fixes a nasty bug that causes some candidates to be lost because `cl-sort` is destructive.

**Comment by dgutov** [comment]
@PythonNut Why don't you update your previous comment instead?

**Comment by bbatsov** [comment]
@dgutov I'd also like to see some development here (and not only me). Plenty of folks feel that the inability to deal with any sort of non-prefix candidates if the only major shortcoming for company. Can't we just handle the case when the backend handles the filtering of the candidates. E.g. CIDER supports both matching of word starts (wots -> with-output-to-string) and a true fuzzy matching, but the candidates returned by the backend are simply ignored by the UI, as they don't share the completion prefix. I'm thinking a simple solution be to just expand such leading characters into a full prefix when you receive some response from the backend. //cc @alexander-yakushev

**Comment by dgutov** [comment]
@bbatsov External fuzzy matching is a bit of a different issue.

Bad news there: `completion-at-point` doesn't support fuzzy matching performed by the external process. You can see that, for instance, by using `M-x completion-at-point`: there won't be any fuzzy matches there; and `company-capf` reuses its filtering logic.

Even if the completion function returns fuzzy matches, the "completion table" API obligates the consumer to call `all-completions` on it (because, for one thing, the table might not be pre-filtered). We've had a long-ish conversation with Stefan about it, but it's sort of hanging unfinished now.

So, as I see, your options are:

* Create a built-in Company backend, in addition to the `completion-at-point-functions` element. You can support fuzzy matching in it.
* File an Emacs bug for `completion-at-point`, asking to support "fuzzy" completion tables. I'll try to, at least, compile the highlights of the related discussion and post them in it. But naturally, anything that comes of that won't help in the currently released Emacs versions.

> I'm thinking a simple solution be to just expand such leading characters into a full prefix when you receive some response from the backend.

That might work, but it will look ugly in the completion popup.

**Comment by PythonNut** [comment]
I suppose the next question (other than the rearchitecture around capf) is how to support fuzzy highlighting in company. Is there any way to do that easily?

**Comment by bbatsov** [comment]
You you can take some pointers from `ido-flx` I guess. There's highlighting of the matching characters there, which looks pretty good.

**Comment by PythonNut** [comment]
@bbatsov I mean, how do we put arbitrary highlighting on `company` candidates.

**Comment by dgutov** [comment]
That might also be solved via a change to `completion-at-point-funtions` API. And a tweak to the handling of the `match` action in `company-backends`.

**Comment by Fuco1** [comment]
I haven't read all the discussion, but the part about a C external program caught my attention.

Some month ago I wrote https://github.com/Fuco1/yafmp which is something like `flx` but

- In C (maybe not an advantage :D)
- Uses much faster scoring algorithm (O(m*n) dynamic programming).  Note that the logic behind is roughly the same (substr bonus is not implemented yet, but that can be added easily), so the quality of the matches is comparable to `flx` already.
- Can be made to operate in a server mode (not yet implemented), when it caches the heatmaps and you just feed it lists of strings and it ranks them.  On my tests I could run 10k strings under 100ms, and that wasn't even very optimized.

Having said that, `flx` is actually really fast in elisp as well, and could be made much faster using vectors instead of lists.  The caching works per "candidate" not "group", so over time it builds the cache for all the strings you are getting back from your backend (each candidate is considered separately, this is the crucial insight).  Plus, if speed is really a concern, one could pre-filter and only kick in ranking later (note that prefiltering could be done without regexp alltogether just looking for a subsequence match, which I'm sure could be written to be much faster than regexp as well).

The only real issue I see here which was menitioned is that the backend can take a long time to generate the candidates.

**Comment by bbatsov** [comment]
Let's add @lewang to this discussion as well.

**Comment by lewang** [comment]
I welcome all innovation in this field.  The reality is I use helm without fuzzy matching.  The interface is just too usable.

I've made several efforts to deeply integrate flx into helm and sadly have been distracted/discouraged somewhere along the way each time (working with Thierry is not the easiest, and I don't think he really sees the value of fuzzy matching).

@Fuco1 I haven't tried yafmp yet, but it could be another way forward.  I will add that in actual usage, the ability for substring matches to overtake abbreviation matches **is** important.  It means that you rarely have to change parts of the query already typed.

I would also welcome any PRs or ideas to improve performance of flx.  IIRC I stopped tweaking with it when it was fast enough in the majority of the use cases.

**Comment by Fuco1** [comment]
> I've made several efforts to deeply integrate flx into helm and sadly have been distracted/discouraged somewhere along the way each time (working with Thierry is not the easiest, and I don't think he really sees the value of fuzzy matching).

Which is one of the reasons I wrote sallet... and there is also ivy and other packages where people got tired of helm's rather peculiar philosopy.  Helm is too ad-hoc on a lot of places, and tbh, I find it not too usable.  But let's not get offtopic.

@lewang yafmp (as the name suggests) is mostly a proof of concept thing.  I took the algorithm from flx (the heatmaps mostly, that is genius :)) and reworked the matching/scoring part, where I don't iterate over all matches but instead build the score incrementally in time proportional only to the length of the pattern, not number of matches.

I tried this in elisp too but elisp has really bad data structures for this kind of programming... you could do it with vectors but I haven't had the nerve to try and port it over :)

Having said that, in practice it rarely happens that the growth is exponential, so that is of relatively minor concern (it blows mostly if the candidates are long and repetitive).  The C version is still thousands of times faster, but being an external program is a major PITA to distribute, so unless we could get it inside emacs I don't see that as a viable option.

**Comment by dgutov** [comment]
> unless we could get it inside emacs I don't see that as a viable option

We could, though someone should double-check that the piping overhead does not offset the performance gains too much.

On the other hand, like you said, flx is pretty fast already. Maybe it could incorporate the changes from your scoring algorithm, too.

**Comment by Fuco1** [comment]
> We could, though someone should double-check that the piping overhead does not offset the performance gains too much.

I ment that it would really be a part of emacs, exposed as a function `string-score-flx` (or some better name, indicating the algorithm used), so there would be no pipe involved.

> On the other hand, like you said, flx is pretty fast already. Maybe it could incorporate the changes from your scoring algorithm, too.

That's definitely possible, I might get back to the idea of porting it there.

**Comment by dgutov** [comment]
> it would really be a part of emacs, exposed as a function

Oh, that's also possible indeed.

**Comment by PythonNut** [comment]
First, I would absolutely love an even faster Elisp fuzzy matching method, (be it an improvement on `flx` or a new system entirely).

But one thing to definitely point out is that the fuzzy _scoring_ runs on a sliding scale. If it's too slow, we can trivially back off on the number of candidates to consider. The strategy of sorting the candidates by length and taking the first `n` of them seems to work very well. On fast machines, we might have `n=500` and on slow machines, we might have `n=50`. In some cases (esp, when `n<50`), it can keep `flx` from looking far into the future (that is, small inputs with very long matches). Faster _scoring_ means a proportionally larger `n`.

Here's a fun plot based purely on casual empirical observations.
![figure_1](https://cloud.githubusercontent.com/assets/5009546/8992614/6962eb08-36b4-11e5-8576-df246ba7b53b.png)

But this is all relatively secondary. Fast machines (Quad i7) can already achieve `n=1000` with almost no lag, so all we really worry about is slower machines.

-----------------------------------

Slower machines have problems with fuzzy _matching_. Unlike sorting, matching is a hard limit because you must match against every possible candidate. I currently I, rather naïvely, implement matching this way:
```emacs
(let*
  (regexp (concat "\\`"
            (mapconcat
              (lambda (x)
                (concat "[^" (string x) "]*?" (string x)))
              infix
              "")))
  (candidates (cl-remove-if-not
                (apply-partially 'string-match-p regexp)
                (all-completions prefix table predicate))))
```
With this code, slower laptops are already unusable. This is without scoring of any kind. I'm no Elisp expert, so I'd love it if some of you people could suggest ways of accelerating this step.

**Comment by Fuco1** [comment]
Please, no sorting on length... that's _terrible_.

If you want further speedups, then start scoring only when the pattern is some number of letters long.  On 2 or 3 letters it's still not super efficient.

Re your code: `apply-partially` is slow as HELL!!!, so is everything in CL.  Use simple loops and simplest possible forms if you go for performance.

**Comment by PythonNut** [comment]
> Please, no sorting on length... that's terrible.

I don't actually quite see how it's terrible. Could you elaborate?

> Re your code: apply-partially is slow as HELL!!!, so is everything in CL. Use simple loops and simplest possible forms if you go for performance.

Good to know.

**Comment by wasamasa** [comment]
@PythonNut The best candidate is not necessarily the shortest, especially if you do weighting on boundaries like flx does.

**Comment by PythonNut** [comment]
@dgutov do you know of a function I can wrap that will only set the `completion-style` for `company`? I'd like to start moving in the direction of a `company-flx` package, and I don't want to just override the completion style for everything.

**Comment by dgutov** [comment]
> I don't want to just override the completion style for everything

I'd do just that (why not?), but you can add an around-advice to `company-capf` instead.

**Comment by PythonNut** [comment]
Alright since fuzzy matching if working for `company-capf`, and we have a concrete way forward to bring this support to other backends (porting to `company-capf`), I think all of the conditions for this issue have been met.

**Comment by dgutov** [comment]
Also see `company-dabbrev-code-completion-styles` in the latest master.
