### ISSUE TITLE
Completion in Shell Mode is case-sensitive

### ISSUE THREAD

**Issue by egarrulo** [company-mode/company-mode#481]
Hello Dmitry,

Company is mostly case-sensitive in Shell Mode.  I said "mostly" because case-insensitive completion sometimes works, albeit I couldn't reproduce the behaviour consistently.  `pcomplete-ignore-case` is `t`.  I have also tried `M-x pcomplete`, but it *never* completes.  Here is the output of `company-diag` when trying to complete `down` to `Downloads`:

    Emacs 24.5.1 (x86_64-unknown-linux-gnu) of 2015-06-27 on debian
    Company 0.9.0-cvs

    company-backends: (company-jedi company-emacs-eclim company-bbdb company-css company-semantic company-clang company-xcode company-cmake company-capf
                  (company-dabbrev-code company-gtags company-etags company-keywords)
                  company-oddmuse company-files company-dabbrev)

    Used backend: company-capf
    Prefix: "down"
    Completions: none

See for comparison, the output for `Down`:

    Emacs 24.5.1 (x86_64-unknown-linux-gnu) of 2015-06-27 on debian
    Company 0.9.0-cvs

    company-backends: (company-jedi company-emacs-eclim company-bbdb company-css company-semantic company-clang company-xcode company-cmake company-capf
                  (company-dabbrev-code company-gtags company-etags company-keywords)
                  company-oddmuse company-files company-dabbrev)

    Used backend: company-capf
    Prefix: "Down"
    Completions:
      #("Downloads/" 0 4 (face completions-common-part) 4 5 (face (completions-first-difference)))

Thank you for your attention.

**Comment by dgutov** [comment]
Hi!

Hm, it works for me. If I set `pcomplete-ignore-case` to `t` and type `cd dow`, I get `Downloads` among the suggestions. If I set `pcomplete-ignore-case` to `nil`, I get no suggestions in the same situation.

Do you have a reliable counter-example scenario starting with `emacs -Q`? If you do, what if, instead of using `company-mode`, you try to invoke the default completion UI, by pressing `C-M-i`? Do you get the desired result  then?

Emacs version 25.0.91.4 here (the branch `emacs-25`).

**Comment by egarrulo** [comment]
Unfortunately I cannot reproduce the problem with `emacs -Q`.  Of course, there is something in my configuration that interferes with it.  Does Company use PComplete in Shell Mode?

**Comment by dgutov** [comment]
> Does Company use PComplete in Shell Mode?

Since the above variable has an effect, apparently so. But company-mode doesn't use pcomplete directly, it just delegates to `comint-completion-at-point` (which apparently is the only element `shell-mode` adds to `completion-at-point-functions`).

**Comment by egarrulo** [comment]
Thanks.  Then I will investigate what `comint-completion-at-point` does and report back.

**Comment by egarrulo** [comment]
I have tried to investigate the issue, and checked the return value of `comint-filename-completion` - which seems the lowest-level called function in this case - but the return value contains gibberish, even when successful, and I have no idea about how to interpret it.  Does company interpret it?

Anyway, Company completes even when PComplete fails to do so. Funny.

**Comment by dgutov** [comment]
> comint-filename-completion - which seems the lowest-level called function in this case

Lowest? As you can see from the definition, it delegates to `comint--complete-file-name-data`.

> but the return value contains gibberish, even when successful

The return value is a list conforming to the expected return value of a `completion-at-point-functions` element (beg position, end position, completion table, properties). But the completion table, and the `:exit-function` values in this list, are both lambdas. Since you're probably running the byte-compiled code, the lambdas are byte-compiled as well, that's why they're looking funny.

To see more legible return values, try re-evaluating the `comint` package from the source code: visit `lisp/comint.el` (hopefully you do have the sources for your current Emacs installed), and call `M-x eval-buffer`.

After that, if you repeat the same steps in the current Emacs session, the return values should look better. However, you're unlikely to learn much from them directly. What's usually helpful, is instrumenting functions lower in the stack, such as `comint-completion-file-name-table`, which is called by `table`.

> and I have no idea about how to interpret it. Does company interpret it?

Yes, `company-capf` does that.

**Comment by egarrulo** [comment]
Dear Dmitry,

I have succeeded in reproducing the problem from `emacs -Q`, without activating Company, therefore it is an Emacs bug, that I am reporting.

Thanks for your assistance.

**Comment by dgutov** [comment]
@egarrulo, thanks for doing the investigation. I'll close this when I see that bug report.

**Comment by egarrulo** [comment]
Regrettably, I rushed to a conclusion, sorry. After further investigation, I have determined that completion by `pcomplete` may fail, whilst completion by `completion-at-point` always succeeds.  Since Company uses `completion-at-point`, there still is something that interferes with it in my configuration. Unfortunately, my Emacs Lisp debugging skills are limited, therefore I will just endure this malfunctioning.

**Comment by dgutov** [comment]
I'm sorry to hear that.

Does anything change if you `(setq completion-ignore-case t)` as well? It doesn't seem required here, but I've managed to trigger a remotely related error, see http://debbugs.gnu.org/23117.

What's the value of `completion-at-point-functions` in your shell-mode buffers?

**Comment by egarrulo** [comment]
Hi Dmitry!  Thank you very much for your support.  Yes, `completion-ignore-case` does impact completion, and I haven't experienced the problem any more with `(setq completion-ignore-case t)`, whilst reverting `completion-ignore-case` to `nil` breaks completion immediately.

**Comment by dgutov** [comment]
Great! Time to close this, then.
