### ISSUE TITLE
No meta for automatically started single completions?

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#548]
In emacs-lisp-mode, if I type

```
(define-ad
```

I get a single completion `(define-advice`, with `vice` highlighted. However, the `meta` information (in the minibuffer) isn't displayed. If I run `company-manual-begin`, on the other hand, I do get the `meta` tooltip.

Is this expected?

**Comment by cpitclaudel** [comment]
Hmm, actually, I do get the `meta` label, but much later.

**Comment by cpitclaudel** [comment]
`company-echo-delay` is set to `0.01`.

**Comment by dgutov** [comment]
`flyspell-mode` seems to be culprit here as well, with its `sit-for` for 3 seconds (default value of `flyspell-delay`).

This problem seems to go away if I use `run-with-timer` instead of `run-with-idle-timer` in `company-echo-show-when-idle`, but I'm not sure what other consequences that might have. Extra redisplays at odd times, maybe (those happen when a timer fires)?

**Comment by cpitclaudel** [comment]
Fascinating. Flyspell *is* annoying. Should we report a bug about it? This sit-for thing is relatively unpleasant.
I'm not sure about run-with-timer either. I could try it locally and report problems.

**Comment by dgutov** [comment]
> Should we report a bug about it?

Maybe. I've not sure what's the design considerations were, but at least it should be able to avoid the `sit-for` call when `flyspell-generic-check-word-predicate` returns nil (which is the effect of `flyspell-prog-mode`).

> I could try it locally and report problems.

Please do.

**Comment by dgutov** [comment]
That's some thorough testing! :smile:

**Comment by dgutov** [comment]
I've pushed an equivalent change. Thanks, and closing.
