### ISSUE TITLE
why this disable in Emacs started?

### ISSUE THREAD

**Issue by gold-king** [company-mode/company-mode#587]
Hi guys:
It's a ploblem in here.

My config file with `company` is following:

```
;;; package --- Summary
;;; Commentary:
;;; Code:
(autoload 'company "company code mode" t nil)
(autoload 'company-elisp "elisp" t nil)
(autoload 'company-etags "etags" t nil)
(autoload 'company-files "files" t nil)
(autoload 'company-gtags "gtags" t nil)
(autoload 'company-manual-begin "company-manual" t nil)
(autoload 'company-complete "complete company" t nil)

'(global-company-mode 1)
'(company-idle-delay 0)

(provide 'mine-company)
;;; mine-company.el ends here
```

Is any wrong here?

Now, i need `M-x company-mode` when Emacs started  to use.

**Comment by syohex** [comment]
Quote is not necessary at `'(global-company-mode 1)`. You should write `(global-company-mode 1)` instead of `'(global-company-mode 1)`. And autoload configurations are not necessary if you install company-mode by package manager like package.el, el-get etc. And you should use `custom-set-variables` for customize variables.

```lisp
(custom-set-variables
 '(company-idle-delay 0))
(global-company-mode 1)

(provide 'mine-company)
```

**Comment by dgutov** [comment]
> Is any wrong here?

Basically, everything. Looks like you copied the contents from somewhere, but not from the official documentation. And see the comment above for a better advice.
