### ISSUE TITLE
Emacs version dependency is now wrong

### ISSUE THREAD

**Issue by purcell** [company-mode/company-mode#604]
The code uses `user-error`, from Emacs 24.3, but reports a dependency on a lower Emacs version, and includes a patched version of `defvar-local`, which was added in the same version. Either the dep should be updated, or the use of `user-error` should be dropped.

**Comment by purcell** [comment]
P.S. `package-lint` detects this, so you might consider adding checks to the build process.

**Comment by dgutov** [comment]
Oh, sorry I missed that. But since the call happens only when we catch a `user-error` ourselves, it seems the worst thing the 24.1/2 users should experience now is a byte-compilation warning.

> Either the dep should be updated

Do you think it's time to bump the dependency as well? See also https://github.com/dgutov/diff-hl/pull/81.

**Comment by purcell** [comment]
> Do you think it's time to bump the dependency as well? See also dgutov/diff-hl#81.

I'm fine whatever you decide, as long as the deps match up. 24.3 is pretty reasonable IMO.

**Comment by dgutov** [comment]
And done. Thanks for `package-lint`, I'll try using it manually for the time being.
