### ISSUE TITLE
company-mode can't complete long candidates in sh-mode

### ISSUE THREAD

**Issue by alipoor90** [company-mode/company-mode#624]
![screenshot from 2016-12-25 12-21-34](https://cloud.githubusercontent.com/assets/8583960/21470410/eb8bbe98-ca9c-11e6-9041-3e3136c9b5fb.png)
  
  
    
and this is what happens when I press RET:
  

    
![screenshot from 2016-12-25 12-22-14](https://cloud.githubusercontent.com/assets/8583960/21470411/0b3e02f0-ca9d-11e6-8ffe-a5c16bf495d5.png)
  
  
  
  
but the ELPA auto-complete-mode completes this long function name correctly. (but doesn't support quoted variable names completion and this is one of the reasons I'm using company-mode) 
Thanks

**Comment by dgutov** [comment]
Hi!

How do I reproduce this? E.g. how do I get it to suggest the current file's function at all?

**Comment by alipoor90** [comment]
GNU Emacs 25.1.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.4) of 2016-12-15
company-0.9.2

[functions.txt](https://github.com/company-mode/company-mode/files/672339/functions.txt)

1) open this file
2) M-x sh-mode (this should recognize the shebang line and take you to bash-script mode)
3) M-x company-mode

and it should give you suggestions, define a new long name function/variable and ...

Thanks

**Comment by dgutov** [comment]
Thanks. I though I was doing exactly that, but apparently not. I can reproduce this now.

It's a problem in Emacs (which was apparent from the outset, since the backend is `company-capf`), and it goes like this: the completion function takes the generated IMenu index to get the list of functions.

IMenu, however, uses `imenu-max-item-length` to truncate the lengths of its items.

So please `M-x report-emacs-bug` so we can get this fixed, one way or another. In the meantime, you can customize `imenu-max-item-length` to some larger value as a workaround.

**Comment by dgutov** [comment]
To be clear, it's a bug in `sh-mode`, not in IMenu.
