### ISSUE TITLE
Unable to auto-complete with `)` when using electric-pair or smartparens

### ISSUE THREAD

**Issue by ivanbrennan** [company-mode/company-mode#650]
I've added <kbd>(</kbd> and <kbd>)</kbd> to company-auto-complete-chars in order auto-complete function-names and arguments more fluidly. While <kbd>(</kbd> works as expected, <kbd>)</kbd> fails to complete the selected candidate if either electric-pair-mode or smartparens are enabled.

To repro:
  - start Emacs with this minimal init.el
```emacs-lisp
(require 'package)
(package-initialize)
(require 'company)

(setq company-backends '(company-dabbrev)
      company-auto-complete-chars '(?\s ?\( ?\) ?\, ?\.)
      company-auto-complete t)

(global-set-key [tab] 'company-complete-common)

(global-company-mode +1)

(electric-pair-mode  +1)
```
  - `M-x find-file` example.rb
  - insert the following (█ is the cursor)
```ruby
def method1(x,y)
end

def method2(p,q)
end

argument1 = 1
argument2 = 2

meth█
```
  - hit <kbd>tab</kbd>
    - completes common prefix: `method█`
    - lists candidates `method1`, `method2`
  - type <kbd>(</kbd>
    - auto-completes selected candidate: `method1(█`
  - insert `arg` and hit <kbd>tab</kbd>
    - completes common prefix: `method1(argument█`
    - lists candidates `argument1`, `argument2`
  - type <kbd>,</kbd>
    - auto-completes selected candidate: `method1(argument1,█`
  - insert ` arg` and hit <kbd>tab</kbd>
    - completes common prefix: `method1(argument1, argument█`
    - lists candidates `argument1`, `argument2`
  - type <kbd>)</kbd>
    - no auto-completion occurs: `method1(argument1, argument)█`

This happens if either electric-pair-mode or smartparens (or both) are enabled, and I've tried with and without smartparens-strict-mode (it made no difference). If both are *disabled*, the behavior of <kbd>)</kbd> is still a little surprising: typing <kbd>)</kbd> to close out an argument list leaves the common prefix before the <kbd>)</kbd> and only after a 1 second delay is the selected candidate completed.

If I enter a <kbd>)</kbd> where there's no matching <kbd>(</kbd>, like `method1)`, it auto-completes right away like the other auto-complete-chars (<kbd>(</kbd>, <kbd>,</kbd>, <kbd>.</kbd>, <kbd>space</kbd>), regardless whether smartparens or electric-pair modes are enabled.

I'm not sure whether this is best raised as an issue here or at smartparens, so apologies if I should have posted there. Hoping someone can clarify what's going on.

**Comment by dgutov** [comment]
In my testing, with `electric-pair-mode` on, typing `(` on the second step also inserts `)` after the cursor, like expected of `electric-pair-mode`. Then, when you type `)` at the last step, the paren doesn't actually get inserted because a matching one is already present in the buffer.

That makes the following check fail in `company--incremental-p`:

```el
(> (point-max) company--point-max)
```

which means "the last command didn't increase the value of point-max". I wonder if that condition is really necessary for the auto-completion to be used. If there are no counter-examples, I should be able to move the `company-auto-complete-p` clause from `company--continue-failed` up to `company--continue` before the "incremental fail".

To be continued.

**Comment by dgutov** [comment]
Pushed a fix, please try it out.

**Comment by ivanbrennan** [comment]
@dgutov Works great, thanks!
