### ISSUE TITLE
Async backends cause pseudo-tooltip to flicker

### ISSUE THREAD

**Issue by cpitclaudel** [company-mode/company-mode#654]
Here's an example:

```
(setq-local lexical-binding t)

(defun company-async--accept-output (prefix callback proc str)
  (funcall callback (all-completions prefix (split-string str " ")))
  (set-process-filter proc t))

(defun company-async--candidates (prefix callback)
  (let ((process-connection-type nil)
        (proc (start-process "echo" nil "bash" "-c"
                             "echo aaaaaaaaaaaaaaaa aaaaaaaaaaaaaaab aaaaaaaaaaaaaaac")))
    (set-process-filter proc
                        (lambda (proc str) (company-async--accept-output prefix callback proc str)))))

(defun company-async-backend (command &optional arg &rest _)
  "Async backend."
  (interactive '(interactive))
  (pcase command
    (`prefix (company-grab-symbol))
    (`candidates `(:async . ,(lambda (cb) (company-async--candidates arg cb))))
    (`no-cache t)))

(setq-local company-backends '(company-async-backend))

;; type 'aaaaa' here and observe the flickering
```

It's pretty clear why this happens (the callback isn't invoked before returning to Emacs' main loop, so company hides its pop-up, but it's still rather distracting.

Can you think of good workarounds?  I can think of a few options:

1. Let backends handle the refinement of `company-candidates-cache`.  This works for some uses of no-cache, as long as extending the prefix never causes new candidates to appear — this isn't the case for the ELisp backend, IIRC.  Disadvantage: the backend will end up duplicating (in ELisp) some of the logic of the async completion engine.

2. In async mode, don't hide the pseudo tooltip until results come back (or add a potentially customizable delay)

3. In async mode, use the completion cache to filter matches until results come back.  This could be expressed as a new return value for `no-cache`.

Let me know if I missed something simple!

**Comment by cpitclaudel** [comment]
More searching points to https://github.com/company-mode/company-mode/issues/510 , though that issue didn't have an example or potential solutions.

**Comment by cpitclaudel** [comment]
As a not to make future readers' lives easier, here's what the workaround discussed at https://github.com/abingham/emacs-ycmd/issues/264#issuecomment-183160402 may look like:

```
(defun company-async-backend (command &optional arg &rest _)
  "Async backend."
  (interactive '(interactive))
  (pcase command
    (`prefix (company-grab-symbol))
    (`candidates
     (let ((callback nil)
           (results nil))
       (company-async--candidates arg (lambda (res)
                                        (setq results res)
                                        (when callback (funcall callback results))))
       (accept-process-output nil 0.01)
       (or results
           `(:async . ,(lambda (cb) (setq callback cb))))))
    (`no-cache t)))
```

@dgutov Comments welcome on this implementation (It's not an actual solution, of course)

**Comment by cpitclaudel** [comment]
(Note: I had to add a loop around the accept-process-output call, and to do the timing myself to handle chunked output).

**Comment by dgutov** [comment]
As you've noticed, this issue is a duplicate. See also #580 for a related discussion.

So far, I'm not sold on any proposed solution (and a good one should handle the "no cache" option too). And I think we should approach this from the UI side first.

Another thing: adding a backend-specific cache shouldn't be too hard, so I'm not eager to complicate the built-in cache just to handle some easier cases. Further, `completion-at-point-functions` have their own caches (when necessary), so down the like, like discussed with Stefan, we might remove the cache functionality entirely.

1. If the backend can work with cache, they can use one internally before responding to `candidates`, and dynamically choose whether to use the synchronous or asynchronous convention.

2. Don't hide and do what? Aside from the implementation difficulties, how would that look to the user?

Show a blank popup? Then there would still be "blinking" inside that popup when the completions appear.

Show the old list of completions? Then the user might be misled into thinking that the list hasn't changed, if the backend takes a while to reply, the moment when the list refreshes will be arbitrary.

3. And when the result comes, the list will abruptly change? What if the user was just then looking at the first completion and moved to press Return, to get it inserted? The list refreshes, something else gets inserted instead.

The workaround you mentioned should help, but it's up to each individual backend. Basically, it moves the mode of operation from asynchronous to "synchronous, with 10ms timeout". The exact number must change from backend to backend, but that's something to try.

Have you looked into how other editors handle this? IIRC Atom and/or VS Code have asynchronous APIs for completion sources.

So far I'm inclined toward option 2, with some loading indicator (this one would affect its own kind of blinking, but at least the area is small).

But taking into account the require-match feature, and the fact that the above might still be a tad annoying, maybe switching to the synchronous mode as soon as popup has appeared would not be the worst idea either.

**Comment by cpitclaudel** [comment]
Thanks for your thorough answer Dmitry!

> Have you looked into how other editors handle this? IIRC Atom and/or VS Code have asynchronous APIs for completion sources.

I have not.  Switching to synchronous could be a good idea.  Otherwise, the loading indicator could consist in dimming the completions, maybe?  But Emacs faces don't have a good story about dimming.

**Comment by dgutov** [comment]
> Switching to synchronous could be a good idea.

That would increase the average typing latency, though, even if the user has no intention of using completion for a particular expression.

> Otherwise, the loading indicator could consist in dimming the completions, maybe? But Emacs faces don't have a good story about dimming.

Dimming is one option (maybe solvable by auto-generating faces), another it to use a spinner (maybe even a textual one like in https://github.com/Malabarba/spinner.el), or simply an ellipsis, at the top of the bottom of the popup (the lines currently filled with solid color). I don't think implementing the visual part is going to be a huge problem, especially if the latencies are generally small.

Rather, I'd like to know if it would make a sensible user experience, and whether the other editors made the choice to go this route.

**Comment by cpitclaudel** [comment]
>> Switching to synchronous could be a good idea.

> That would increase the average typing latency, though, even if the user has no intention of using completion for a particular expression.

Yes, that's true.  Tricky.  I think the loading indicator option would probably be the best, then.  I'll try to investigate other editors, but I don't have much time atm.

Thanks for all the ideas and the cool work!

**Comment by dgutov** [comment]
> I still see flickers once , or twice

That's the "imperfect" part: if you type several chars faster than the server responds, it will flicker. This looks harder to solve.

Thanks for the feedback, I'd also like to hear from somebody using MacOS in particular (IIRC it has/had some performance problems with the event loop).

**Comment by tigersoldier** [comment]
> I'd also like to hear from somebody using MacOS in particular

I'm using macOS. Haven't tried the branch on Linux though.

**Comment by dgutov** [comment]
OK, I added a minor tweak and pushed to master. Please report any regressions (increased latency, sluggish UI, freezes, etc). Feedback welcome from all.

@Sarcasm, forgot to mention you, but this might be of interest to you as well.

**Comment by Sarcasm** [comment]
I was following the issue, I just compared the before/after and it works great, thank you! :+1:
