### ISSUE TITLE
blinking popup when company-irony is grouped with company-files

### ISSUE THREAD

**Issue by Dickby** [company-mode/company-mode#670]
Hi, 
I use company-irony as a company backend.
I set company-idle-delay to immediate, now if the company popup opens automatically, every time i add a new character the popup blinks, which is rather distracting.
This doesn't happen if i start company-irony manually, it also stops if i press `M-n` to select the next candidate, after that the popup stops blinking on new entered characters.
Is this the right place to report this or is this more a company-irony problem?
Thanks.

**Comment by dgutov** [comment]
Does it also happen if you don't "set company-idle-delay to immediate"?

**Comment by Dickby** [comment]
Yes, with the company-idle-delay set to 'seconds 0.5', i get the same behaviour

**Comment by Dickby** [comment]
It seems to be something in my configuration.
If i company and irony manually after starting emacs with `-Q` it doesn't happen.
I will check what exactly triggers this behaviour and report here.
I leave this issue open for now.

**Comment by Dickby** [comment]
It seems to be not my comfiguration, if I use company-clang as a completion backend it's not blinking, but with company-irony it is.

**Comment by dgutov** [comment]
Sounds like #654, except `company-irony` doesn't seem to disable the cache. So I'm not sure what can be the problem.

**Comment by Dickby** [comment]
I figured out, that it has nothing to do with irony. my c/c++ company configuration looks like:
```elisp
  (add-hook 'c-mode-common-hook (lambda ()
  				  (add-to-list (make-local-variable 'company-backends)
  					       (list 'company-files 'company-c-headers 'company-irony))))
```
if  I take `company-files` out of this list, the blinking stops.
Is there a way to enable `company-files` without having this blinking?

**Comment by dgutov** [comment]
Not currently, no. It's a consequence of the current limited approach to caching completion results.

Blinking occurs when we have an asynchronous backend that doesn't use the built-in caching mechanism (and doesn't have an internal one implemented in Elisp either).

The built-in cache, like other company-mode features, treats the grouped backend like one big backend. As a result, when at least one backend in the group disables caching (`company-files` does that because it has an internal cache), the built-in cache is disabled for the whole group.

I believe the way to go here is for each backend to maintain an independent cache. We should also see whether there are things company-mode could do to make implementing it easier.

**Comment by dgutov** [comment]
Should be much improved in the current master. But a per-backend cache is still a good idea.
