### ISSUE TITLE
Adding backend name in the popup

### ISSUE THREAD

**Issue by huseyinyilmaz** [company-mode/company-mode#691]
Hello,
I have been using vim for last couple weeks and I found one particular functionality really useful.

https://cl.ly/2I3B1M0O2F1r

Here in auto-complete menu, they show backend name next to autocompletion candidate.
This is so helpful for 2 reasons.
1) With this, I know which context, candidate came from. Is candidate shown because because word was used in the same file before? or is it coming from a type system like flow? or is it coming from static analysis backend.
2) It helps me understand which part of the autocompletion is working and which part is not working. it makes debugging vim a lot easier.

I think it would be a really helpful to have an option to add backend name to menu. So I would know what is enabled and what is not.

Also can you direct me to resource for how to debug company-mode. As a daily emacs user, company-mode is a black box for me. Specifically I would like to find out.

Thanks

**Comment by dgutov** [comment]
The backends are free to output anything they want as the completion annotation, including the backend name. It's not something I'd want to see, though: when a lot of popup line say `[flow]`, it's clearly redundant. Even if not all lines do.

It would be nice to allow some sort of templating for the popup display, of course, but someone else will have to tackle that feature, probably.

If you are a backend author, going the annotation route for debugging should be the easiest.

> Is candidate shown because because word was used in the same file before? or is it coming from a type system like flow?

First of all, you can look at the mode-line; unless you're using Powerline or a similar package, the mode-line should show the backend which is currently used. Or you can evaluate (`M-:`) `company-backend`, switch to the Messages buffer and see the result.

If the backend is a a group, though, evaluating `(get-text-property 0 'company-backend (nth company-selection company-candidates))` can let you know the specific backend. If it's nil, the first one in the group; otherwise, the result should be the backend name.

> Specifically I would like to find out.

...what?

**Comment by huseyinyilmaz** [comment]
Hey,
Sorry about half sentence at the end of my message. Looks like it was not the best monday for me :)
Anyway what I was going to say was this: Company mode works really good but the problem is, it is really hard to debug for me. When I add a new backend, I open a file that my new backend supposed to get activated and I try to get some response from company mode. Specifically some backends needs a lot of tweaking so seeing if my configuration is working is really hard. In short, having visibility over what company mode doing would be really nice. Currently it is magically working but I have no idea which part of my setup is working and which part of is not working.

So my suggestion is to add some functionality to helps users to debug their setup. For instance, I think one of the following would be a very nice to have:

* Like I mentioned, having backend name next to candidate. This is valuable because it helps us understand how intelligent the suggestion is, is it some text based suggestion or is it coming from type system. Also helps debugging what is working and what is not.
* Getting debug logs when I turn a flag. I could use logs to debug my setup.
* Having an interface like flycheck debugging interface: M-x flycheck-verify-setup

**Comment by dgutov** [comment]
In addition to what I mentioned in the previous message, we have `M-x company-diag`.

**Comment by huseyinyilmaz** [comment]
Thank you for your help @dgutov. it seems like I can use company-diag to debug my setup. It shows candidate sources which I did not have before.
