### ISSUE TITLE
Interoperate with mhtml-mode

### ISSUE THREAD

**Issue by tromey** [company-mode/company-mode#709]
Emacs 26 includes `mhtml-mode`, a derivative of HTML mode that handles embedded JS and CSS.

`company-css.el` uses `web-mode-language-at-pos` -- it should also use the mhtml equivalent.  mhtml-mode works by putting text properties in the buffer, but maybe it would be best if I added some convenience function to mhtml-mode for company to call?

**Comment by dgutov** [comment]
> mhtml-mode works by putting text properties in the buffer, but maybe it would be best if I added some convenience function to mhtml-mode for company to call?

It's your call. It the long run, though, I imagine we'll need a `-function` variable or a hook for this purpose, so that other modes can integrate with this as well.

**Comment by tromey** [comment]
Good idea, I'll send a patch to that effect to emacs-devel for discussion.

**Comment by tromey** [comment]
@dgutov ok, I sent a note, please take a look.

**Comment by titaniumbones** [comment]
I'm just fixing up my personal init files & hoping to switch to both mhtml & company -- is this issue resolved now?

**Comment by dgutov** [comment]
I remember that I responded, but it's not trivial to find that thread now. I kind of remember that it was left unresolved. :-(

@tromey

**Comment by dgutov** [comment]
Nothing had been added, and currently the solution looks rather crufty:

```el
(when-let ((value (get-text-property (point) 'mhtml-submode)))
  (equal "CSS" (mhtml--submode-name value)))
```

In any case, we have deprecated `company-css` in favor of the built-in css-mode completion. And we don't have any built-in completion for HTML or JS. With the minor exception that `company-dabbrev-code` could use the particular minor mode while looking up properties at point, but that would require additional changes to limit the regions it scans as well.

So most of the changes should pertain to third-party code, and for LSP users the problem is hopefully already solved anyway.
