### ISSUE TITLE
The completion menu does not trigger for backward-kill-word and kill-line

### ISSUE THREAD

**Issue by cyrus-and** [company-mode/company-mode#907]
I have the following in my `.emacs`:

```lisp
(add-to-list 'company-begin-commands #'delete-backward-char)
(add-to-list 'company-begin-commands #'backward-delete-char-untabify)

(add-to-list 'company-begin-commands #'backward-kill-word)
(add-to-list 'company-begin-commands #'kill-line)
```

While the first two work as expected, `backward-kill-word` and `kill-line` don't.

(Related to #639.)

**Comment by isolet** [comment]
Any new of this?

**Comment by dgutov** [comment]
This reason is, both `backward-kill-word` and `kill-line` set `this-command` to `kill-region` for certain reasons.

Consequently, if you add `kill-region` to `company-begin-commands`, this will have the desired effect. Possible unfortunate side-effect, though, is that will then accept (probably) any command which calls `kill-region` internally.

**Comment by cyrus-and** [comment]
@dgutov thanks, it makes sense. Feel free to close this.
