### ISSUE TITLE
company-mode breaks yasnippet in this case

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#925]
The completion candicates(c-mode):
```
int Err_foo = 1;
int Err_bar = 2;
int Err_hello = 3;
```
And the snippet:
```
return Err${1:_foo};
```

In the snippet field, I input something(like "_"). The completion menu pops up. Then I select a item(like "_bar") and commit it. yasnippet is breaked with an error message:
```
[yas] Committing snippets. Action would destroy a protection overlay.
```

**Comment by netjune** [comment]
I think it may be because company mode midified the text out of the field of the snippet. (It is "Err" before "_bar"). If it only replace "_" with the new text "_bar", and doesn't touch "Err", then yasnippet maybe won't complain.

**Comment by dgutov** [comment]
@npostavs What do you think?

**Comment by npostavs** [comment]
Yes, it's been a long-standing assumption in yasnippet that commands shouldn't modify text outside the current field. But there is the `yas-inhibit-overlay-modification-protection` to disable this. I added it in response to a similar report company-mode (joaotavora/yasnippet#982). The option remains `nil` by default since I still consider it somewhat experimental, but I believe it should cover this case too.

**Comment by dgutov** [comment]
@npostavs Do you think `company--insert-candidate` should let-bind this variable to t?
