### ISSUE TITLE
Add info manual

### ISSUE THREAD

**Issue by skangas** [company-mode/company-mode#926]
It would be very useful to have an Info manual for this package. I realize it could be a big task, so please consider this issue request to be only for a manual which includes the bare minimum: what you need to get up and running. It could be extended later.

Thanks in advance.

**Comment by dgutov** [comment]
Help welcome. I'm not well-versed in TexInfo myself.

But speaking of "get up and running", do you find the Usage section on the website insufficient?

**Comment by skangas** [comment]
> But speaking of "get up and running", do you find the Usage section on the website insufficient?

It's sufficient to get started using the package, even if it's inconvenient to have to visit a website to read it. It also looks rudimentary, so I'm not sure if there is anything else that would be good to know for a new user such as myself.

**Comment by yugaego** [comment]
For someone who eventually (hopefully) gets to writing a `TextInfo` manual (or any other similar `Company` manual),
the following are the current sources of information that may help to start with it:

-  [`Usage`](http://company-mode.github.io) section on the `Company` homepage.
- [Wiki](https://github.com/company-mode/company-mode/wiki) pages.
- [Discussions](https://github.com/company-mode/company-mode/discussions) section.
- Also probably Issues, especially the ones with the [`question`](https://github.com/company-mode/company-mode/issues?q=label%3Aquestion) label.
- Docstrings can be looked up in the source or with the standard `Emacs` commands `C-h v` and `C-h f`.
  - *One* of the ways to discover which variables/functions are available is to use the command `occur`
    -  f.i. `M-x occur <RET> ^(defcustom` or `M-s o <RET> ^(defun`

**Comment by yugaego** [comment]
@dgutov, Supposedly I might give it a try, at least starting with the basic structure (chapters/sections) and doing it slowly.

[I'm still considering because I'm not sure at this stage if it'd be really feasible for me.]
  
Considering such a manual, would it go into the `/doc` directory and:
consist of `.texi` files only (i.e. a smaller version of the [auctex](https://github.com/emacsmirror/auctex/tree/master/doc) documentation)?

[Hence, to format `texi` files properly, it'd be advisable to read (skim through) `Texinfo` manual first.]

I see some of the `GNU ELPA` packages have `/doc` (or variations) directory with a mix of files in it, but it looks like often they either aren't intended to be added to the `Info Directory` or require additional steps to do so.
Examples: [swiper](https://github.com/abo-abo/swiper/tree/master/doc), [transient](https://github.com/magit/transient/tree/master/docs), [yasnippet](https://github.com/joaotavora/yasnippet/tree/master/doc), [magit](https://github.com/magit/magit/tree/master/Documentation).

[Debbugs](https://github.com/emacsmirror/debbugs) approach is a unique one with `texi` files in the root of the tree.

Any ideas, feedback on this? Thank you.

**Comment by yugaego** [comment]
>  require additional steps to do so.

It seems I was wrong, as most of those documentations showed up after `Emacs` restart (probably I missed to ~revert *Info Directory*). I've skimmed through those newly installed manuals. After that this task started to seem much more approachable. Hence, I'm assigning it to myself and going to move forward with it little by little, unless you've got anything else on your mind 😉

**Comment by dgutov** [comment]
@yugaego It's very good that it fixed itself, because I've been trying to avoid that area of knowledge for a long time. :persevere:

Work on the manual is appreciated, though I really hope you then stay around to update it as well. :slightly_smiling_face: 

The other two tasks I've been eyeing (for myself, really) are more low-level: #340, #992.

#519 seems easy enough, however (I really dropped the ball on this one). Do you think "good first issue" can apply to a task like that?

**Comment by yugaego** [comment]
> though I really hope you then stay around to update it as well. 

I hope so too.

Thanks for linking the other tasks, I'll take a look.

**Comment by dgutov** [comment]
@skangas The manual is now in!

Comments and improvements welcome.

**Comment by skangas** [comment]
Many thanks to everyone involved!

**Comment by yugaego** [comment]
The online version of the [User Manual](https://company-mode.github.io/manual/) is now live.

**Comment by dgutov** [comment]
I've posted the announcement to Reddit.

People praise the manual but are somewhat unhappy about the color theme: https://www.reddit.com/r/emacs/comments/rqewjw/companymode_now_has_a_manual/

Guess we'll need to do something about that.

**Comment by yugaego** [comment]
> Guess we'll need to do something about that.

It's easy to make the font darker. The question is should it be applied to the homepage too? Currently the manual styles are homepage styles with tiny specifics added.

**Comment by dgutov** [comment]
> The question is should it be applied to the homepage too?

Probably, yes.

A wholesale change of theme is on the table too (the current one looked modern several years ago, but not such much today), though it's admittedly a bigger effort.

**Comment by yugaego** [comment]
Follow-up PR: https://github.com/company-mode/company-mode.github.com/pull/14
